// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file geometry_msgs.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "geometry_msgs.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace geometry_msgs {

namespace msg {

namespace dds_ {



Point32_::Point32_()
{
}

Point32_::~Point32_()
{
}

Point32_::Point32_(
        const Point32_& x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

Point32_::Point32_(
        Point32_&& x) noexcept
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

Point32_& Point32_::operator =(
        const Point32_& x)
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    return *this;
}

Point32_& Point32_::operator =(
        Point32_&& x) noexcept
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    return *this;
}

bool Point32_::operator ==(
        const Point32_& x) const
{
    return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z);
}

bool Point32_::operator !=(
        const Point32_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void Point32_::x(
        float _x)
{
    m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
float Point32_::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
float& Point32_::x()
{
    return m_x;
}


/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void Point32_::y(
        float _y)
{
    m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
float Point32_::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
float& Point32_::y()
{
    return m_y;
}


/*!
 * @brief This function sets a value in member z
 * @param _z New value for member z
 */
void Point32_::z(
        float _z)
{
    m_z = _z;
}

/*!
 * @brief This function returns the value of member z
 * @return Value of member z
 */
float Point32_::z() const
{
    return m_z;
}

/*!
 * @brief This function returns a reference to member z
 * @return Reference to member z
 */
float& Point32_::z()
{
    return m_z;
}






Polygon_::Polygon_()
{
}

Polygon_::~Polygon_()
{
}

Polygon_::Polygon_(
        const Polygon_& x)
{
    m_points = x.m_points;
}

Polygon_::Polygon_(
        Polygon_&& x) noexcept
{
    m_points = std::move(x.m_points);
}

Polygon_& Polygon_::operator =(
        const Polygon_& x)
{

    m_points = x.m_points;
    return *this;
}

Polygon_& Polygon_::operator =(
        Polygon_&& x) noexcept
{

    m_points = std::move(x.m_points);
    return *this;
}

bool Polygon_::operator ==(
        const Polygon_& x) const
{
    return (m_points == x.m_points);
}

bool Polygon_::operator !=(
        const Polygon_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member points
 * @param _points New value to be copied in member points
 */
void Polygon_::points(
        const std::vector<geometry_msgs::msg::dds_::Point32_>& _points)
{
    m_points = _points;
}

/*!
 * @brief This function moves the value in member points
 * @param _points New value to be moved in member points
 */
void Polygon_::points(
        std::vector<geometry_msgs::msg::dds_::Point32_>&& _points)
{
    m_points = std::move(_points);
}

/*!
 * @brief This function returns a constant reference to member points
 * @return Constant reference to member points
 */
const std::vector<geometry_msgs::msg::dds_::Point32_>& Polygon_::points() const
{
    return m_points;
}

/*!
 * @brief This function returns a reference to member points
 * @return Reference to member points
 */
std::vector<geometry_msgs::msg::dds_::Point32_>& Polygon_::points()
{
    return m_points;
}




PolygonStamped_::PolygonStamped_()
{
}

PolygonStamped_::~PolygonStamped_()
{
}

PolygonStamped_::PolygonStamped_(
        const PolygonStamped_& x)
{
    m_header = x.m_header;
    m_polygon = x.m_polygon;
}

PolygonStamped_::PolygonStamped_(
        PolygonStamped_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_polygon = std::move(x.m_polygon);
}

PolygonStamped_& PolygonStamped_::operator =(
        const PolygonStamped_& x)
{

    m_header = x.m_header;
    m_polygon = x.m_polygon;
    return *this;
}

PolygonStamped_& PolygonStamped_::operator =(
        PolygonStamped_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_polygon = std::move(x.m_polygon);
    return *this;
}

bool PolygonStamped_::operator ==(
        const PolygonStamped_& x) const
{
    return (m_header == x.m_header &&
           m_polygon == x.m_polygon);
}

bool PolygonStamped_::operator !=(
        const PolygonStamped_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void PolygonStamped_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void PolygonStamped_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& PolygonStamped_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& PolygonStamped_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member polygon
 * @param _polygon New value to be copied in member polygon
 */
void PolygonStamped_::polygon(
        const geometry_msgs::msg::dds_::Polygon_& _polygon)
{
    m_polygon = _polygon;
}

/*!
 * @brief This function moves the value in member polygon
 * @param _polygon New value to be moved in member polygon
 */
void PolygonStamped_::polygon(
        geometry_msgs::msg::dds_::Polygon_&& _polygon)
{
    m_polygon = std::move(_polygon);
}

/*!
 * @brief This function returns a constant reference to member polygon
 * @return Constant reference to member polygon
 */
const geometry_msgs::msg::dds_::Polygon_& PolygonStamped_::polygon() const
{
    return m_polygon;
}

/*!
 * @brief This function returns a reference to member polygon
 * @return Reference to member polygon
 */
geometry_msgs::msg::dds_::Polygon_& PolygonStamped_::polygon()
{
    return m_polygon;
}




Point_::Point_()
{
}

Point_::~Point_()
{
}

Point_::Point_(
        const Point_& x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

Point_::Point_(
        Point_&& x) noexcept
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

Point_& Point_::operator =(
        const Point_& x)
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    return *this;
}

Point_& Point_::operator =(
        Point_&& x) noexcept
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    return *this;
}

bool Point_::operator ==(
        const Point_& x) const
{
    return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z);
}

bool Point_::operator !=(
        const Point_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void Point_::x(
        double _x)
{
    m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
double Point_::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
double& Point_::x()
{
    return m_x;
}


/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void Point_::y(
        double _y)
{
    m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
double Point_::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
double& Point_::y()
{
    return m_y;
}


/*!
 * @brief This function sets a value in member z
 * @param _z New value for member z
 */
void Point_::z(
        double _z)
{
    m_z = _z;
}

/*!
 * @brief This function returns the value of member z
 * @return Value of member z
 */
double Point_::z() const
{
    return m_z;
}

/*!
 * @brief This function returns a reference to member z
 * @return Reference to member z
 */
double& Point_::z()
{
    return m_z;
}




Quaternion_::Quaternion_()
{
}

Quaternion_::~Quaternion_()
{
}

Quaternion_::Quaternion_(
        const Quaternion_& x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
}

Quaternion_::Quaternion_(
        Quaternion_&& x) noexcept
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
}

Quaternion_& Quaternion_::operator =(
        const Quaternion_& x)
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
    return *this;
}

Quaternion_& Quaternion_::operator =(
        Quaternion_&& x) noexcept
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
    return *this;
}

bool Quaternion_::operator ==(
        const Quaternion_& x) const
{
    return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z &&
           m_w == x.m_w);
}

bool Quaternion_::operator !=(
        const Quaternion_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void Quaternion_::x(
        double _x)
{
    m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
double Quaternion_::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
double& Quaternion_::x()
{
    return m_x;
}


/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void Quaternion_::y(
        double _y)
{
    m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
double Quaternion_::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
double& Quaternion_::y()
{
    return m_y;
}


/*!
 * @brief This function sets a value in member z
 * @param _z New value for member z
 */
void Quaternion_::z(
        double _z)
{
    m_z = _z;
}

/*!
 * @brief This function returns the value of member z
 * @return Value of member z
 */
double Quaternion_::z() const
{
    return m_z;
}

/*!
 * @brief This function returns a reference to member z
 * @return Reference to member z
 */
double& Quaternion_::z()
{
    return m_z;
}


/*!
 * @brief This function sets a value in member w
 * @param _w New value for member w
 */
void Quaternion_::w(
        double _w)
{
    m_w = _w;
}

/*!
 * @brief This function returns the value of member w
 * @return Value of member w
 */
double Quaternion_::w() const
{
    return m_w;
}

/*!
 * @brief This function returns a reference to member w
 * @return Reference to member w
 */
double& Quaternion_::w()
{
    return m_w;
}




Transform_::Transform_()
{
}

Transform_::~Transform_()
{
}

Transform_::Transform_(
        const Transform_& x)
{
    m_translation = x.m_translation;
    m_rotation = x.m_rotation;
}

Transform_::Transform_(
        Transform_&& x) noexcept
{
    m_translation = std::move(x.m_translation);
    m_rotation = std::move(x.m_rotation);
}

Transform_& Transform_::operator =(
        const Transform_& x)
{

    m_translation = x.m_translation;
    m_rotation = x.m_rotation;
    return *this;
}

Transform_& Transform_::operator =(
        Transform_&& x) noexcept
{

    m_translation = std::move(x.m_translation);
    m_rotation = std::move(x.m_rotation);
    return *this;
}

bool Transform_::operator ==(
        const Transform_& x) const
{
    return (m_translation == x.m_translation &&
           m_rotation == x.m_rotation);
}

bool Transform_::operator !=(
        const Transform_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member translation
 * @param _translation New value to be copied in member translation
 */
void Transform_::translation(
        const geometry_msgs::msg::dds_::Point_& _translation)
{
    m_translation = _translation;
}

/*!
 * @brief This function moves the value in member translation
 * @param _translation New value to be moved in member translation
 */
void Transform_::translation(
        geometry_msgs::msg::dds_::Point_&& _translation)
{
    m_translation = std::move(_translation);
}

/*!
 * @brief This function returns a constant reference to member translation
 * @return Constant reference to member translation
 */
const geometry_msgs::msg::dds_::Point_& Transform_::translation() const
{
    return m_translation;
}

/*!
 * @brief This function returns a reference to member translation
 * @return Reference to member translation
 */
geometry_msgs::msg::dds_::Point_& Transform_::translation()
{
    return m_translation;
}


/*!
 * @brief This function copies the value in member rotation
 * @param _rotation New value to be copied in member rotation
 */
void Transform_::rotation(
        const geometry_msgs::msg::dds_::Quaternion_& _rotation)
{
    m_rotation = _rotation;
}

/*!
 * @brief This function moves the value in member rotation
 * @param _rotation New value to be moved in member rotation
 */
void Transform_::rotation(
        geometry_msgs::msg::dds_::Quaternion_&& _rotation)
{
    m_rotation = std::move(_rotation);
}

/*!
 * @brief This function returns a constant reference to member rotation
 * @return Constant reference to member rotation
 */
const geometry_msgs::msg::dds_::Quaternion_& Transform_::rotation() const
{
    return m_rotation;
}

/*!
 * @brief This function returns a reference to member rotation
 * @return Reference to member rotation
 */
geometry_msgs::msg::dds_::Quaternion_& Transform_::rotation()
{
    return m_rotation;
}




TransformStamped_::TransformStamped_()
{
}

TransformStamped_::~TransformStamped_()
{
}

TransformStamped_::TransformStamped_(
        const TransformStamped_& x)
{
    m_header = x.m_header;
    m_child_frame_id = x.m_child_frame_id;
    m_transform = x.m_transform;
}

TransformStamped_::TransformStamped_(
        TransformStamped_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_child_frame_id = std::move(x.m_child_frame_id);
    m_transform = std::move(x.m_transform);
}

TransformStamped_& TransformStamped_::operator =(
        const TransformStamped_& x)
{

    m_header = x.m_header;
    m_child_frame_id = x.m_child_frame_id;
    m_transform = x.m_transform;
    return *this;
}

TransformStamped_& TransformStamped_::operator =(
        TransformStamped_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_child_frame_id = std::move(x.m_child_frame_id);
    m_transform = std::move(x.m_transform);
    return *this;
}

bool TransformStamped_::operator ==(
        const TransformStamped_& x) const
{
    return (m_header == x.m_header &&
           m_child_frame_id == x.m_child_frame_id &&
           m_transform == x.m_transform);
}

bool TransformStamped_::operator !=(
        const TransformStamped_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void TransformStamped_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void TransformStamped_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& TransformStamped_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& TransformStamped_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member child_frame_id
 * @param _child_frame_id New value to be copied in member child_frame_id
 */
void TransformStamped_::child_frame_id(
        const std::string& _child_frame_id)
{
    m_child_frame_id = _child_frame_id;
}

/*!
 * @brief This function moves the value in member child_frame_id
 * @param _child_frame_id New value to be moved in member child_frame_id
 */
void TransformStamped_::child_frame_id(
        std::string&& _child_frame_id)
{
    m_child_frame_id = std::move(_child_frame_id);
}

/*!
 * @brief This function returns a constant reference to member child_frame_id
 * @return Constant reference to member child_frame_id
 */
const std::string& TransformStamped_::child_frame_id() const
{
    return m_child_frame_id;
}

/*!
 * @brief This function returns a reference to member child_frame_id
 * @return Reference to member child_frame_id
 */
std::string& TransformStamped_::child_frame_id()
{
    return m_child_frame_id;
}


/*!
 * @brief This function copies the value in member transform
 * @param _transform New value to be copied in member transform
 */
void TransformStamped_::transform(
        const geometry_msgs::msg::dds_::Transform_& _transform)
{
    m_transform = _transform;
}

/*!
 * @brief This function moves the value in member transform
 * @param _transform New value to be moved in member transform
 */
void TransformStamped_::transform(
        geometry_msgs::msg::dds_::Transform_&& _transform)
{
    m_transform = std::move(_transform);
}

/*!
 * @brief This function returns a constant reference to member transform
 * @return Constant reference to member transform
 */
const geometry_msgs::msg::dds_::Transform_& TransformStamped_::transform() const
{
    return m_transform;
}

/*!
 * @brief This function returns a reference to member transform
 * @return Reference to member transform
 */
geometry_msgs::msg::dds_::Transform_& TransformStamped_::transform()
{
    return m_transform;
}




Pose_::Pose_()
{
}

Pose_::~Pose_()
{
}

Pose_::Pose_(
        const Pose_& x)
{
    m_position = x.m_position;
    m_orientation = x.m_orientation;
}

Pose_::Pose_(
        Pose_&& x) noexcept
{
    m_position = std::move(x.m_position);
    m_orientation = std::move(x.m_orientation);
}

Pose_& Pose_::operator =(
        const Pose_& x)
{

    m_position = x.m_position;
    m_orientation = x.m_orientation;
    return *this;
}

Pose_& Pose_::operator =(
        Pose_&& x) noexcept
{

    m_position = std::move(x.m_position);
    m_orientation = std::move(x.m_orientation);
    return *this;
}

bool Pose_::operator ==(
        const Pose_& x) const
{
    return (m_position == x.m_position &&
           m_orientation == x.m_orientation);
}

bool Pose_::operator !=(
        const Pose_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member position
 * @param _position New value to be copied in member position
 */
void Pose_::position(
        const geometry_msgs::msg::dds_::Point_& _position)
{
    m_position = _position;
}

/*!
 * @brief This function moves the value in member position
 * @param _position New value to be moved in member position
 */
void Pose_::position(
        geometry_msgs::msg::dds_::Point_&& _position)
{
    m_position = std::move(_position);
}

/*!
 * @brief This function returns a constant reference to member position
 * @return Constant reference to member position
 */
const geometry_msgs::msg::dds_::Point_& Pose_::position() const
{
    return m_position;
}

/*!
 * @brief This function returns a reference to member position
 * @return Reference to member position
 */
geometry_msgs::msg::dds_::Point_& Pose_::position()
{
    return m_position;
}


/*!
 * @brief This function copies the value in member orientation
 * @param _orientation New value to be copied in member orientation
 */
void Pose_::orientation(
        const geometry_msgs::msg::dds_::Quaternion_& _orientation)
{
    m_orientation = _orientation;
}

/*!
 * @brief This function moves the value in member orientation
 * @param _orientation New value to be moved in member orientation
 */
void Pose_::orientation(
        geometry_msgs::msg::dds_::Quaternion_&& _orientation)
{
    m_orientation = std::move(_orientation);
}

/*!
 * @brief This function returns a constant reference to member orientation
 * @return Constant reference to member orientation
 */
const geometry_msgs::msg::dds_::Quaternion_& Pose_::orientation() const
{
    return m_orientation;
}

/*!
 * @brief This function returns a reference to member orientation
 * @return Reference to member orientation
 */
geometry_msgs::msg::dds_::Quaternion_& Pose_::orientation()
{
    return m_orientation;
}






PoseArray_::PoseArray_()
{
}

PoseArray_::~PoseArray_()
{
}

PoseArray_::PoseArray_(
        const PoseArray_& x)
{
    m_header = x.m_header;
    m_poses = x.m_poses;
}

PoseArray_::PoseArray_(
        PoseArray_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_poses = std::move(x.m_poses);
}

PoseArray_& PoseArray_::operator =(
        const PoseArray_& x)
{

    m_header = x.m_header;
    m_poses = x.m_poses;
    return *this;
}

PoseArray_& PoseArray_::operator =(
        PoseArray_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_poses = std::move(x.m_poses);
    return *this;
}

bool PoseArray_::operator ==(
        const PoseArray_& x) const
{
    return (m_header == x.m_header &&
           m_poses == x.m_poses);
}

bool PoseArray_::operator !=(
        const PoseArray_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void PoseArray_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void PoseArray_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& PoseArray_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& PoseArray_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member poses
 * @param _poses New value to be copied in member poses
 */
void PoseArray_::poses(
        const std::vector<geometry_msgs::msg::dds_::Pose_>& _poses)
{
    m_poses = _poses;
}

/*!
 * @brief This function moves the value in member poses
 * @param _poses New value to be moved in member poses
 */
void PoseArray_::poses(
        std::vector<geometry_msgs::msg::dds_::Pose_>&& _poses)
{
    m_poses = std::move(_poses);
}

/*!
 * @brief This function returns a constant reference to member poses
 * @return Constant reference to member poses
 */
const std::vector<geometry_msgs::msg::dds_::Pose_>& PoseArray_::poses() const
{
    return m_poses;
}

/*!
 * @brief This function returns a reference to member poses
 * @return Reference to member poses
 */
std::vector<geometry_msgs::msg::dds_::Pose_>& PoseArray_::poses()
{
    return m_poses;
}




PoseWithCovariance_::PoseWithCovariance_()
{
}

PoseWithCovariance_::~PoseWithCovariance_()
{
}

PoseWithCovariance_::PoseWithCovariance_(
        const PoseWithCovariance_& x)
{
    m_pose = x.m_pose;
    m_covariance = x.m_covariance;
}

PoseWithCovariance_::PoseWithCovariance_(
        PoseWithCovariance_&& x) noexcept
{
    m_pose = std::move(x.m_pose);
    m_covariance = std::move(x.m_covariance);
}

PoseWithCovariance_& PoseWithCovariance_::operator =(
        const PoseWithCovariance_& x)
{

    m_pose = x.m_pose;
    m_covariance = x.m_covariance;
    return *this;
}

PoseWithCovariance_& PoseWithCovariance_::operator =(
        PoseWithCovariance_&& x) noexcept
{

    m_pose = std::move(x.m_pose);
    m_covariance = std::move(x.m_covariance);
    return *this;
}

bool PoseWithCovariance_::operator ==(
        const PoseWithCovariance_& x) const
{
    return (m_pose == x.m_pose &&
           m_covariance == x.m_covariance);
}

bool PoseWithCovariance_::operator !=(
        const PoseWithCovariance_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member pose
 * @param _pose New value to be copied in member pose
 */
void PoseWithCovariance_::pose(
        const geometry_msgs::msg::dds_::Pose_& _pose)
{
    m_pose = _pose;
}

/*!
 * @brief This function moves the value in member pose
 * @param _pose New value to be moved in member pose
 */
void PoseWithCovariance_::pose(
        geometry_msgs::msg::dds_::Pose_&& _pose)
{
    m_pose = std::move(_pose);
}

/*!
 * @brief This function returns a constant reference to member pose
 * @return Constant reference to member pose
 */
const geometry_msgs::msg::dds_::Pose_& PoseWithCovariance_::pose() const
{
    return m_pose;
}

/*!
 * @brief This function returns a reference to member pose
 * @return Reference to member pose
 */
geometry_msgs::msg::dds_::Pose_& PoseWithCovariance_::pose()
{
    return m_pose;
}


/*!
 * @brief This function copies the value in member covariance
 * @param _covariance New value to be copied in member covariance
 */
void PoseWithCovariance_::covariance(
        const std::array<double, 36>& _covariance)
{
    m_covariance = _covariance;
}

/*!
 * @brief This function moves the value in member covariance
 * @param _covariance New value to be moved in member covariance
 */
void PoseWithCovariance_::covariance(
        std::array<double, 36>&& _covariance)
{
    m_covariance = std::move(_covariance);
}

/*!
 * @brief This function returns a constant reference to member covariance
 * @return Constant reference to member covariance
 */
const std::array<double, 36>& PoseWithCovariance_::covariance() const
{
    return m_covariance;
}

/*!
 * @brief This function returns a reference to member covariance
 * @return Reference to member covariance
 */
std::array<double, 36>& PoseWithCovariance_::covariance()
{
    return m_covariance;
}




PoseStamped_::PoseStamped_()
{
}

PoseStamped_::~PoseStamped_()
{
}

PoseStamped_::PoseStamped_(
        const PoseStamped_& x)
{
    m_header = x.m_header;
    m_pose = x.m_pose;
}

PoseStamped_::PoseStamped_(
        PoseStamped_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_pose = std::move(x.m_pose);
}

PoseStamped_& PoseStamped_::operator =(
        const PoseStamped_& x)
{

    m_header = x.m_header;
    m_pose = x.m_pose;
    return *this;
}

PoseStamped_& PoseStamped_::operator =(
        PoseStamped_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_pose = std::move(x.m_pose);
    return *this;
}

bool PoseStamped_::operator ==(
        const PoseStamped_& x) const
{
    return (m_header == x.m_header &&
           m_pose == x.m_pose);
}

bool PoseStamped_::operator !=(
        const PoseStamped_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void PoseStamped_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void PoseStamped_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& PoseStamped_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& PoseStamped_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member pose
 * @param _pose New value to be copied in member pose
 */
void PoseStamped_::pose(
        const geometry_msgs::msg::dds_::Pose_& _pose)
{
    m_pose = _pose;
}

/*!
 * @brief This function moves the value in member pose
 * @param _pose New value to be moved in member pose
 */
void PoseStamped_::pose(
        geometry_msgs::msg::dds_::Pose_&& _pose)
{
    m_pose = std::move(_pose);
}

/*!
 * @brief This function returns a constant reference to member pose
 * @return Constant reference to member pose
 */
const geometry_msgs::msg::dds_::Pose_& PoseStamped_::pose() const
{
    return m_pose;
}

/*!
 * @brief This function returns a reference to member pose
 * @return Reference to member pose
 */
geometry_msgs::msg::dds_::Pose_& PoseStamped_::pose()
{
    return m_pose;
}




Vector3_::Vector3_()
{
}

Vector3_::~Vector3_()
{
}

Vector3_::Vector3_(
        const Vector3_& x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

Vector3_::Vector3_(
        Vector3_&& x) noexcept
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

Vector3_& Vector3_::operator =(
        const Vector3_& x)
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    return *this;
}

Vector3_& Vector3_::operator =(
        Vector3_&& x) noexcept
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    return *this;
}

bool Vector3_::operator ==(
        const Vector3_& x) const
{
    return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z);
}

bool Vector3_::operator !=(
        const Vector3_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void Vector3_::x(
        double _x)
{
    m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
double Vector3_::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
double& Vector3_::x()
{
    return m_x;
}


/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void Vector3_::y(
        double _y)
{
    m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
double Vector3_::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
double& Vector3_::y()
{
    return m_y;
}


/*!
 * @brief This function sets a value in member z
 * @param _z New value for member z
 */
void Vector3_::z(
        double _z)
{
    m_z = _z;
}

/*!
 * @brief This function returns the value of member z
 * @return Value of member z
 */
double Vector3_::z() const
{
    return m_z;
}

/*!
 * @brief This function returns a reference to member z
 * @return Reference to member z
 */
double& Vector3_::z()
{
    return m_z;
}




Twist_::Twist_()
{
}

Twist_::~Twist_()
{
}

Twist_::Twist_(
        const Twist_& x)
{
    m_linear = x.m_linear;
    m_angular = x.m_angular;
}

Twist_::Twist_(
        Twist_&& x) noexcept
{
    m_linear = std::move(x.m_linear);
    m_angular = std::move(x.m_angular);
}

Twist_& Twist_::operator =(
        const Twist_& x)
{

    m_linear = x.m_linear;
    m_angular = x.m_angular;
    return *this;
}

Twist_& Twist_::operator =(
        Twist_&& x) noexcept
{

    m_linear = std::move(x.m_linear);
    m_angular = std::move(x.m_angular);
    return *this;
}

bool Twist_::operator ==(
        const Twist_& x) const
{
    return (m_linear == x.m_linear &&
           m_angular == x.m_angular);
}

bool Twist_::operator !=(
        const Twist_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member linear
 * @param _linear New value to be copied in member linear
 */
void Twist_::linear(
        const geometry_msgs::msg::dds_::Vector3_& _linear)
{
    m_linear = _linear;
}

/*!
 * @brief This function moves the value in member linear
 * @param _linear New value to be moved in member linear
 */
void Twist_::linear(
        geometry_msgs::msg::dds_::Vector3_&& _linear)
{
    m_linear = std::move(_linear);
}

/*!
 * @brief This function returns a constant reference to member linear
 * @return Constant reference to member linear
 */
const geometry_msgs::msg::dds_::Vector3_& Twist_::linear() const
{
    return m_linear;
}

/*!
 * @brief This function returns a reference to member linear
 * @return Reference to member linear
 */
geometry_msgs::msg::dds_::Vector3_& Twist_::linear()
{
    return m_linear;
}


/*!
 * @brief This function copies the value in member angular
 * @param _angular New value to be copied in member angular
 */
void Twist_::angular(
        const geometry_msgs::msg::dds_::Vector3_& _angular)
{
    m_angular = _angular;
}

/*!
 * @brief This function moves the value in member angular
 * @param _angular New value to be moved in member angular
 */
void Twist_::angular(
        geometry_msgs::msg::dds_::Vector3_&& _angular)
{
    m_angular = std::move(_angular);
}

/*!
 * @brief This function returns a constant reference to member angular
 * @return Constant reference to member angular
 */
const geometry_msgs::msg::dds_::Vector3_& Twist_::angular() const
{
    return m_angular;
}

/*!
 * @brief This function returns a reference to member angular
 * @return Reference to member angular
 */
geometry_msgs::msg::dds_::Vector3_& Twist_::angular()
{
    return m_angular;
}




TwistWithCovariance_::TwistWithCovariance_()
{
}

TwistWithCovariance_::~TwistWithCovariance_()
{
}

TwistWithCovariance_::TwistWithCovariance_(
        const TwistWithCovariance_& x)
{
    m_twist = x.m_twist;
    m_covariance = x.m_covariance;
}

TwistWithCovariance_::TwistWithCovariance_(
        TwistWithCovariance_&& x) noexcept
{
    m_twist = std::move(x.m_twist);
    m_covariance = std::move(x.m_covariance);
}

TwistWithCovariance_& TwistWithCovariance_::operator =(
        const TwistWithCovariance_& x)
{

    m_twist = x.m_twist;
    m_covariance = x.m_covariance;
    return *this;
}

TwistWithCovariance_& TwistWithCovariance_::operator =(
        TwistWithCovariance_&& x) noexcept
{

    m_twist = std::move(x.m_twist);
    m_covariance = std::move(x.m_covariance);
    return *this;
}

bool TwistWithCovariance_::operator ==(
        const TwistWithCovariance_& x) const
{
    return (m_twist == x.m_twist &&
           m_covariance == x.m_covariance);
}

bool TwistWithCovariance_::operator !=(
        const TwistWithCovariance_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member twist
 * @param _twist New value to be copied in member twist
 */
void TwistWithCovariance_::twist(
        const geometry_msgs::msg::dds_::Twist_& _twist)
{
    m_twist = _twist;
}

/*!
 * @brief This function moves the value in member twist
 * @param _twist New value to be moved in member twist
 */
void TwistWithCovariance_::twist(
        geometry_msgs::msg::dds_::Twist_&& _twist)
{
    m_twist = std::move(_twist);
}

/*!
 * @brief This function returns a constant reference to member twist
 * @return Constant reference to member twist
 */
const geometry_msgs::msg::dds_::Twist_& TwistWithCovariance_::twist() const
{
    return m_twist;
}

/*!
 * @brief This function returns a reference to member twist
 * @return Reference to member twist
 */
geometry_msgs::msg::dds_::Twist_& TwistWithCovariance_::twist()
{
    return m_twist;
}


/*!
 * @brief This function copies the value in member covariance
 * @param _covariance New value to be copied in member covariance
 */
void TwistWithCovariance_::covariance(
        const std::array<double, 36>& _covariance)
{
    m_covariance = _covariance;
}

/*!
 * @brief This function moves the value in member covariance
 * @param _covariance New value to be moved in member covariance
 */
void TwistWithCovariance_::covariance(
        std::array<double, 36>&& _covariance)
{
    m_covariance = std::move(_covariance);
}

/*!
 * @brief This function returns a constant reference to member covariance
 * @return Constant reference to member covariance
 */
const std::array<double, 36>& TwistWithCovariance_::covariance() const
{
    return m_covariance;
}

/*!
 * @brief This function returns a reference to member covariance
 * @return Reference to member covariance
 */
std::array<double, 36>& TwistWithCovariance_::covariance()
{
    return m_covariance;
}




} // namespace dds_


} // namespace msg


} // namespace geometry_msgs
// Include auxiliary functions like for serializing/deserializing.
#include "geometry_msgsCdrAux.ipp"

