// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file nav_msgs.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "nav_msgs.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace nav_msgs {

namespace msg {

namespace dds_ {



Odometry_::Odometry_()
{
}

Odometry_::~Odometry_()
{
}

Odometry_::Odometry_(
        const Odometry_& x)
{
    m_header = x.m_header;
    m_child_frame_id = x.m_child_frame_id;
    m_pose = x.m_pose;
    m_twist = x.m_twist;
}

Odometry_::Odometry_(
        Odometry_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_child_frame_id = std::move(x.m_child_frame_id);
    m_pose = std::move(x.m_pose);
    m_twist = std::move(x.m_twist);
}

Odometry_& Odometry_::operator =(
        const Odometry_& x)
{

    m_header = x.m_header;
    m_child_frame_id = x.m_child_frame_id;
    m_pose = x.m_pose;
    m_twist = x.m_twist;
    return *this;
}

Odometry_& Odometry_::operator =(
        Odometry_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_child_frame_id = std::move(x.m_child_frame_id);
    m_pose = std::move(x.m_pose);
    m_twist = std::move(x.m_twist);
    return *this;
}

bool Odometry_::operator ==(
        const Odometry_& x) const
{
    return (m_header == x.m_header &&
           m_child_frame_id == x.m_child_frame_id &&
           m_pose == x.m_pose &&
           m_twist == x.m_twist);
}

bool Odometry_::operator !=(
        const Odometry_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void Odometry_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void Odometry_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& Odometry_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& Odometry_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member child_frame_id
 * @param _child_frame_id New value to be copied in member child_frame_id
 */
void Odometry_::child_frame_id(
        const std::string& _child_frame_id)
{
    m_child_frame_id = _child_frame_id;
}

/*!
 * @brief This function moves the value in member child_frame_id
 * @param _child_frame_id New value to be moved in member child_frame_id
 */
void Odometry_::child_frame_id(
        std::string&& _child_frame_id)
{
    m_child_frame_id = std::move(_child_frame_id);
}

/*!
 * @brief This function returns a constant reference to member child_frame_id
 * @return Constant reference to member child_frame_id
 */
const std::string& Odometry_::child_frame_id() const
{
    return m_child_frame_id;
}

/*!
 * @brief This function returns a reference to member child_frame_id
 * @return Reference to member child_frame_id
 */
std::string& Odometry_::child_frame_id()
{
    return m_child_frame_id;
}


/*!
 * @brief This function copies the value in member pose
 * @param _pose New value to be copied in member pose
 */
void Odometry_::pose(
        const geometry_msgs::msg::dds_::PoseWithCovariance_& _pose)
{
    m_pose = _pose;
}

/*!
 * @brief This function moves the value in member pose
 * @param _pose New value to be moved in member pose
 */
void Odometry_::pose(
        geometry_msgs::msg::dds_::PoseWithCovariance_&& _pose)
{
    m_pose = std::move(_pose);
}

/*!
 * @brief This function returns a constant reference to member pose
 * @return Constant reference to member pose
 */
const geometry_msgs::msg::dds_::PoseWithCovariance_& Odometry_::pose() const
{
    return m_pose;
}

/*!
 * @brief This function returns a reference to member pose
 * @return Reference to member pose
 */
geometry_msgs::msg::dds_::PoseWithCovariance_& Odometry_::pose()
{
    return m_pose;
}


/*!
 * @brief This function copies the value in member twist
 * @param _twist New value to be copied in member twist
 */
void Odometry_::twist(
        const geometry_msgs::msg::dds_::TwistWithCovariance_& _twist)
{
    m_twist = _twist;
}

/*!
 * @brief This function moves the value in member twist
 * @param _twist New value to be moved in member twist
 */
void Odometry_::twist(
        geometry_msgs::msg::dds_::TwistWithCovariance_&& _twist)
{
    m_twist = std::move(_twist);
}

/*!
 * @brief This function returns a constant reference to member twist
 * @return Constant reference to member twist
 */
const geometry_msgs::msg::dds_::TwistWithCovariance_& Odometry_::twist() const
{
    return m_twist;
}

/*!
 * @brief This function returns a reference to member twist
 * @return Reference to member twist
 */
geometry_msgs::msg::dds_::TwistWithCovariance_& Odometry_::twist()
{
    return m_twist;
}




MapMetaData_::MapMetaData_()
{
}

MapMetaData_::~MapMetaData_()
{
}

MapMetaData_::MapMetaData_(
        const MapMetaData_& x)
{
    m_map_load_time = x.m_map_load_time;
    m_resolution = x.m_resolution;
    m_width = x.m_width;
    m_height = x.m_height;
    m_origin = x.m_origin;
}

MapMetaData_::MapMetaData_(
        MapMetaData_&& x) noexcept
{
    m_map_load_time = std::move(x.m_map_load_time);
    m_resolution = x.m_resolution;
    m_width = x.m_width;
    m_height = x.m_height;
    m_origin = std::move(x.m_origin);
}

MapMetaData_& MapMetaData_::operator =(
        const MapMetaData_& x)
{

    m_map_load_time = x.m_map_load_time;
    m_resolution = x.m_resolution;
    m_width = x.m_width;
    m_height = x.m_height;
    m_origin = x.m_origin;
    return *this;
}

MapMetaData_& MapMetaData_::operator =(
        MapMetaData_&& x) noexcept
{

    m_map_load_time = std::move(x.m_map_load_time);
    m_resolution = x.m_resolution;
    m_width = x.m_width;
    m_height = x.m_height;
    m_origin = std::move(x.m_origin);
    return *this;
}

bool MapMetaData_::operator ==(
        const MapMetaData_& x) const
{
    return (m_map_load_time == x.m_map_load_time &&
           m_resolution == x.m_resolution &&
           m_width == x.m_width &&
           m_height == x.m_height &&
           m_origin == x.m_origin);
}

bool MapMetaData_::operator !=(
        const MapMetaData_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member map_load_time
 * @param _map_load_time New value to be copied in member map_load_time
 */
void MapMetaData_::map_load_time(
        const std_msgs::msg::TimeStandard& _map_load_time)
{
    m_map_load_time = _map_load_time;
}

/*!
 * @brief This function moves the value in member map_load_time
 * @param _map_load_time New value to be moved in member map_load_time
 */
void MapMetaData_::map_load_time(
        std_msgs::msg::TimeStandard&& _map_load_time)
{
    m_map_load_time = std::move(_map_load_time);
}

/*!
 * @brief This function returns a constant reference to member map_load_time
 * @return Constant reference to member map_load_time
 */
const std_msgs::msg::TimeStandard& MapMetaData_::map_load_time() const
{
    return m_map_load_time;
}

/*!
 * @brief This function returns a reference to member map_load_time
 * @return Reference to member map_load_time
 */
std_msgs::msg::TimeStandard& MapMetaData_::map_load_time()
{
    return m_map_load_time;
}


/*!
 * @brief This function sets a value in member resolution
 * @param _resolution New value for member resolution
 */
void MapMetaData_::resolution(
        float _resolution)
{
    m_resolution = _resolution;
}

/*!
 * @brief This function returns the value of member resolution
 * @return Value of member resolution
 */
float MapMetaData_::resolution() const
{
    return m_resolution;
}

/*!
 * @brief This function returns a reference to member resolution
 * @return Reference to member resolution
 */
float& MapMetaData_::resolution()
{
    return m_resolution;
}


/*!
 * @brief This function sets a value in member width
 * @param _width New value for member width
 */
void MapMetaData_::width(
        uint32_t _width)
{
    m_width = _width;
}

/*!
 * @brief This function returns the value of member width
 * @return Value of member width
 */
uint32_t MapMetaData_::width() const
{
    return m_width;
}

/*!
 * @brief This function returns a reference to member width
 * @return Reference to member width
 */
uint32_t& MapMetaData_::width()
{
    return m_width;
}


/*!
 * @brief This function sets a value in member height
 * @param _height New value for member height
 */
void MapMetaData_::height(
        uint32_t _height)
{
    m_height = _height;
}

/*!
 * @brief This function returns the value of member height
 * @return Value of member height
 */
uint32_t MapMetaData_::height() const
{
    return m_height;
}

/*!
 * @brief This function returns a reference to member height
 * @return Reference to member height
 */
uint32_t& MapMetaData_::height()
{
    return m_height;
}


/*!
 * @brief This function copies the value in member origin
 * @param _origin New value to be copied in member origin
 */
void MapMetaData_::origin(
        const geometry_msgs::msg::dds_::Pose_& _origin)
{
    m_origin = _origin;
}

/*!
 * @brief This function moves the value in member origin
 * @param _origin New value to be moved in member origin
 */
void MapMetaData_::origin(
        geometry_msgs::msg::dds_::Pose_&& _origin)
{
    m_origin = std::move(_origin);
}

/*!
 * @brief This function returns a constant reference to member origin
 * @return Constant reference to member origin
 */
const geometry_msgs::msg::dds_::Pose_& MapMetaData_::origin() const
{
    return m_origin;
}

/*!
 * @brief This function returns a reference to member origin
 * @return Reference to member origin
 */
geometry_msgs::msg::dds_::Pose_& MapMetaData_::origin()
{
    return m_origin;
}






OccupancyGrid_::OccupancyGrid_()
{
}

OccupancyGrid_::~OccupancyGrid_()
{
}

OccupancyGrid_::OccupancyGrid_(
        const OccupancyGrid_& x)
{
    m_header = x.m_header;
    m_info = x.m_info;
    m_data = x.m_data;
}

OccupancyGrid_::OccupancyGrid_(
        OccupancyGrid_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_info = std::move(x.m_info);
    m_data = std::move(x.m_data);
}

OccupancyGrid_& OccupancyGrid_::operator =(
        const OccupancyGrid_& x)
{

    m_header = x.m_header;
    m_info = x.m_info;
    m_data = x.m_data;
    return *this;
}

OccupancyGrid_& OccupancyGrid_::operator =(
        OccupancyGrid_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_info = std::move(x.m_info);
    m_data = std::move(x.m_data);
    return *this;
}

bool OccupancyGrid_::operator ==(
        const OccupancyGrid_& x) const
{
    return (m_header == x.m_header &&
           m_info == x.m_info &&
           m_data == x.m_data);
}

bool OccupancyGrid_::operator !=(
        const OccupancyGrid_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void OccupancyGrid_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void OccupancyGrid_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& OccupancyGrid_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& OccupancyGrid_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member info
 * @param _info New value to be copied in member info
 */
void OccupancyGrid_::info(
        const nav_msgs::msg::dds_::MapMetaData_& _info)
{
    m_info = _info;
}

/*!
 * @brief This function moves the value in member info
 * @param _info New value to be moved in member info
 */
void OccupancyGrid_::info(
        nav_msgs::msg::dds_::MapMetaData_&& _info)
{
    m_info = std::move(_info);
}

/*!
 * @brief This function returns a constant reference to member info
 * @return Constant reference to member info
 */
const nav_msgs::msg::dds_::MapMetaData_& OccupancyGrid_::info() const
{
    return m_info;
}

/*!
 * @brief This function returns a reference to member info
 * @return Reference to member info
 */
nav_msgs::msg::dds_::MapMetaData_& OccupancyGrid_::info()
{
    return m_info;
}


/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void OccupancyGrid_::data(
        const std::vector<uint8_t>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void OccupancyGrid_::data(
        std::vector<uint8_t>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& OccupancyGrid_::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& OccupancyGrid_::data()
{
    return m_data;
}






Path_::Path_()
{
}

Path_::~Path_()
{
}

Path_::Path_(
        const Path_& x)
{
    m_header = x.m_header;
    m_poses = x.m_poses;
}

Path_::Path_(
        Path_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_poses = std::move(x.m_poses);
}

Path_& Path_::operator =(
        const Path_& x)
{

    m_header = x.m_header;
    m_poses = x.m_poses;
    return *this;
}

Path_& Path_::operator =(
        Path_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_poses = std::move(x.m_poses);
    return *this;
}

bool Path_::operator ==(
        const Path_& x) const
{
    return (m_header == x.m_header &&
           m_poses == x.m_poses);
}

bool Path_::operator !=(
        const Path_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void Path_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void Path_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& Path_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& Path_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member poses
 * @param _poses New value to be copied in member poses
 */
void Path_::poses(
        const std::vector<geometry_msgs::msg::dds_::PoseStamped_>& _poses)
{
    m_poses = _poses;
}

/*!
 * @brief This function moves the value in member poses
 * @param _poses New value to be moved in member poses
 */
void Path_::poses(
        std::vector<geometry_msgs::msg::dds_::PoseStamped_>&& _poses)
{
    m_poses = std::move(_poses);
}

/*!
 * @brief This function returns a constant reference to member poses
 * @return Constant reference to member poses
 */
const std::vector<geometry_msgs::msg::dds_::PoseStamped_>& Path_::poses() const
{
    return m_poses;
}

/*!
 * @brief This function returns a reference to member poses
 * @return Reference to member poses
 */
std::vector<geometry_msgs::msg::dds_::PoseStamped_>& Path_::poses()
{
    return m_poses;
}




PathEvent_::PathEvent_()
{
}

PathEvent_::~PathEvent_()
{
}

PathEvent_::PathEvent_(
        const PathEvent_& x)
{
    m_header = x.m_header;
    m_data = x.m_data;
}

PathEvent_::PathEvent_(
        PathEvent_&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_data = std::move(x.m_data);
}

PathEvent_& PathEvent_::operator =(
        const PathEvent_& x)
{

    m_header = x.m_header;
    m_data = x.m_data;
    return *this;
}

PathEvent_& PathEvent_::operator =(
        PathEvent_&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_data = std::move(x.m_data);
    return *this;
}

bool PathEvent_::operator ==(
        const PathEvent_& x) const
{
    return (m_header == x.m_header &&
           m_data == x.m_data);
}

bool PathEvent_::operator !=(
        const PathEvent_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void PathEvent_::header(
        const std_msgs::msg::HeaderStandard& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void PathEvent_::header(
        std_msgs::msg::HeaderStandard&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::HeaderStandard& PathEvent_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::HeaderStandard& PathEvent_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void PathEvent_::data(
        const std::string& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void PathEvent_::data(
        std::string&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::string& PathEvent_::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::string& PathEvent_::data()
{
    return m_data;
}




} // namespace dds_


} // namespace msg


} // namespace nav_msgs
// Include auxiliary functions like for serializing/deserializing.
#include "nav_msgsCdrAux.ipp"

