// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file rover_msgs.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "rover_msgs.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace rover_msgs {

namespace msg {

namespace dds_ {



RoverInfo_::RoverInfo_()
{
}

RoverInfo_::~RoverInfo_()
{
}

RoverInfo_::RoverInfo_(
        const RoverInfo_& x)
{
    m_footprint = x.m_footprint;
    m_safety_margin = x.m_safety_margin;
    m_min_lin_vel = x.m_min_lin_vel;
    m_max_lin_vel = x.m_max_lin_vel;
    m_min_ang_vel = x.m_min_ang_vel;
    m_max_ang_vel = x.m_max_ang_vel;
    m_max_lin_acc = x.m_max_lin_acc;
    m_max_ang_acc = x.m_max_ang_acc;
    m_max_cen_acc = x.m_max_cen_acc;
    m_lin_resolution = x.m_lin_resolution;
    m_ang_resolution = x.m_ang_resolution;
}

RoverInfo_::RoverInfo_(
        RoverInfo_&& x) noexcept
{
    m_footprint = std::move(x.m_footprint);
    m_safety_margin = x.m_safety_margin;
    m_min_lin_vel = x.m_min_lin_vel;
    m_max_lin_vel = x.m_max_lin_vel;
    m_min_ang_vel = x.m_min_ang_vel;
    m_max_ang_vel = x.m_max_ang_vel;
    m_max_lin_acc = x.m_max_lin_acc;
    m_max_ang_acc = x.m_max_ang_acc;
    m_max_cen_acc = x.m_max_cen_acc;
    m_lin_resolution = x.m_lin_resolution;
    m_ang_resolution = x.m_ang_resolution;
}

RoverInfo_& RoverInfo_::operator =(
        const RoverInfo_& x)
{

    m_footprint = x.m_footprint;
    m_safety_margin = x.m_safety_margin;
    m_min_lin_vel = x.m_min_lin_vel;
    m_max_lin_vel = x.m_max_lin_vel;
    m_min_ang_vel = x.m_min_ang_vel;
    m_max_ang_vel = x.m_max_ang_vel;
    m_max_lin_acc = x.m_max_lin_acc;
    m_max_ang_acc = x.m_max_ang_acc;
    m_max_cen_acc = x.m_max_cen_acc;
    m_lin_resolution = x.m_lin_resolution;
    m_ang_resolution = x.m_ang_resolution;
    return *this;
}

RoverInfo_& RoverInfo_::operator =(
        RoverInfo_&& x) noexcept
{

    m_footprint = std::move(x.m_footprint);
    m_safety_margin = x.m_safety_margin;
    m_min_lin_vel = x.m_min_lin_vel;
    m_max_lin_vel = x.m_max_lin_vel;
    m_min_ang_vel = x.m_min_ang_vel;
    m_max_ang_vel = x.m_max_ang_vel;
    m_max_lin_acc = x.m_max_lin_acc;
    m_max_ang_acc = x.m_max_ang_acc;
    m_max_cen_acc = x.m_max_cen_acc;
    m_lin_resolution = x.m_lin_resolution;
    m_ang_resolution = x.m_ang_resolution;
    return *this;
}

bool RoverInfo_::operator ==(
        const RoverInfo_& x) const
{
    return (m_footprint == x.m_footprint &&
           m_safety_margin == x.m_safety_margin &&
           m_min_lin_vel == x.m_min_lin_vel &&
           m_max_lin_vel == x.m_max_lin_vel &&
           m_min_ang_vel == x.m_min_ang_vel &&
           m_max_ang_vel == x.m_max_ang_vel &&
           m_max_lin_acc == x.m_max_lin_acc &&
           m_max_ang_acc == x.m_max_ang_acc &&
           m_max_cen_acc == x.m_max_cen_acc &&
           m_lin_resolution == x.m_lin_resolution &&
           m_ang_resolution == x.m_ang_resolution);
}

bool RoverInfo_::operator !=(
        const RoverInfo_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member footprint
 * @param _footprint New value to be copied in member footprint
 */
void RoverInfo_::footprint(
        const std::array<double, 6>& _footprint)
{
    m_footprint = _footprint;
}

/*!
 * @brief This function moves the value in member footprint
 * @param _footprint New value to be moved in member footprint
 */
void RoverInfo_::footprint(
        std::array<double, 6>&& _footprint)
{
    m_footprint = std::move(_footprint);
}

/*!
 * @brief This function returns a constant reference to member footprint
 * @return Constant reference to member footprint
 */
const std::array<double, 6>& RoverInfo_::footprint() const
{
    return m_footprint;
}

/*!
 * @brief This function returns a reference to member footprint
 * @return Reference to member footprint
 */
std::array<double, 6>& RoverInfo_::footprint()
{
    return m_footprint;
}


/*!
 * @brief This function sets a value in member safety_margin
 * @param _safety_margin New value for member safety_margin
 */
void RoverInfo_::safety_margin(
        double _safety_margin)
{
    m_safety_margin = _safety_margin;
}

/*!
 * @brief This function returns the value of member safety_margin
 * @return Value of member safety_margin
 */
double RoverInfo_::safety_margin() const
{
    return m_safety_margin;
}

/*!
 * @brief This function returns a reference to member safety_margin
 * @return Reference to member safety_margin
 */
double& RoverInfo_::safety_margin()
{
    return m_safety_margin;
}


/*!
 * @brief This function sets a value in member min_lin_vel
 * @param _min_lin_vel New value for member min_lin_vel
 */
void RoverInfo_::min_lin_vel(
        double _min_lin_vel)
{
    m_min_lin_vel = _min_lin_vel;
}

/*!
 * @brief This function returns the value of member min_lin_vel
 * @return Value of member min_lin_vel
 */
double RoverInfo_::min_lin_vel() const
{
    return m_min_lin_vel;
}

/*!
 * @brief This function returns a reference to member min_lin_vel
 * @return Reference to member min_lin_vel
 */
double& RoverInfo_::min_lin_vel()
{
    return m_min_lin_vel;
}


/*!
 * @brief This function sets a value in member max_lin_vel
 * @param _max_lin_vel New value for member max_lin_vel
 */
void RoverInfo_::max_lin_vel(
        double _max_lin_vel)
{
    m_max_lin_vel = _max_lin_vel;
}

/*!
 * @brief This function returns the value of member max_lin_vel
 * @return Value of member max_lin_vel
 */
double RoverInfo_::max_lin_vel() const
{
    return m_max_lin_vel;
}

/*!
 * @brief This function returns a reference to member max_lin_vel
 * @return Reference to member max_lin_vel
 */
double& RoverInfo_::max_lin_vel()
{
    return m_max_lin_vel;
}


/*!
 * @brief This function sets a value in member min_ang_vel
 * @param _min_ang_vel New value for member min_ang_vel
 */
void RoverInfo_::min_ang_vel(
        double _min_ang_vel)
{
    m_min_ang_vel = _min_ang_vel;
}

/*!
 * @brief This function returns the value of member min_ang_vel
 * @return Value of member min_ang_vel
 */
double RoverInfo_::min_ang_vel() const
{
    return m_min_ang_vel;
}

/*!
 * @brief This function returns a reference to member min_ang_vel
 * @return Reference to member min_ang_vel
 */
double& RoverInfo_::min_ang_vel()
{
    return m_min_ang_vel;
}


/*!
 * @brief This function sets a value in member max_ang_vel
 * @param _max_ang_vel New value for member max_ang_vel
 */
void RoverInfo_::max_ang_vel(
        double _max_ang_vel)
{
    m_max_ang_vel = _max_ang_vel;
}

/*!
 * @brief This function returns the value of member max_ang_vel
 * @return Value of member max_ang_vel
 */
double RoverInfo_::max_ang_vel() const
{
    return m_max_ang_vel;
}

/*!
 * @brief This function returns a reference to member max_ang_vel
 * @return Reference to member max_ang_vel
 */
double& RoverInfo_::max_ang_vel()
{
    return m_max_ang_vel;
}


/*!
 * @brief This function sets a value in member max_lin_acc
 * @param _max_lin_acc New value for member max_lin_acc
 */
void RoverInfo_::max_lin_acc(
        double _max_lin_acc)
{
    m_max_lin_acc = _max_lin_acc;
}

/*!
 * @brief This function returns the value of member max_lin_acc
 * @return Value of member max_lin_acc
 */
double RoverInfo_::max_lin_acc() const
{
    return m_max_lin_acc;
}

/*!
 * @brief This function returns a reference to member max_lin_acc
 * @return Reference to member max_lin_acc
 */
double& RoverInfo_::max_lin_acc()
{
    return m_max_lin_acc;
}


/*!
 * @brief This function sets a value in member max_ang_acc
 * @param _max_ang_acc New value for member max_ang_acc
 */
void RoverInfo_::max_ang_acc(
        double _max_ang_acc)
{
    m_max_ang_acc = _max_ang_acc;
}

/*!
 * @brief This function returns the value of member max_ang_acc
 * @return Value of member max_ang_acc
 */
double RoverInfo_::max_ang_acc() const
{
    return m_max_ang_acc;
}

/*!
 * @brief This function returns a reference to member max_ang_acc
 * @return Reference to member max_ang_acc
 */
double& RoverInfo_::max_ang_acc()
{
    return m_max_ang_acc;
}


/*!
 * @brief This function sets a value in member max_cen_acc
 * @param _max_cen_acc New value for member max_cen_acc
 */
void RoverInfo_::max_cen_acc(
        double _max_cen_acc)
{
    m_max_cen_acc = _max_cen_acc;
}

/*!
 * @brief This function returns the value of member max_cen_acc
 * @return Value of member max_cen_acc
 */
double RoverInfo_::max_cen_acc() const
{
    return m_max_cen_acc;
}

/*!
 * @brief This function returns a reference to member max_cen_acc
 * @return Reference to member max_cen_acc
 */
double& RoverInfo_::max_cen_acc()
{
    return m_max_cen_acc;
}


/*!
 * @brief This function sets a value in member lin_resolution
 * @param _lin_resolution New value for member lin_resolution
 */
void RoverInfo_::lin_resolution(
        double _lin_resolution)
{
    m_lin_resolution = _lin_resolution;
}

/*!
 * @brief This function returns the value of member lin_resolution
 * @return Value of member lin_resolution
 */
double RoverInfo_::lin_resolution() const
{
    return m_lin_resolution;
}

/*!
 * @brief This function returns a reference to member lin_resolution
 * @return Reference to member lin_resolution
 */
double& RoverInfo_::lin_resolution()
{
    return m_lin_resolution;
}


/*!
 * @brief This function sets a value in member ang_resolution
 * @param _ang_resolution New value for member ang_resolution
 */
void RoverInfo_::ang_resolution(
        double _ang_resolution)
{
    m_ang_resolution = _ang_resolution;
}

/*!
 * @brief This function returns the value of member ang_resolution
 * @return Value of member ang_resolution
 */
double RoverInfo_::ang_resolution() const
{
    return m_ang_resolution;
}

/*!
 * @brief This function returns a reference to member ang_resolution
 * @return Reference to member ang_resolution
 */
double& RoverInfo_::ang_resolution()
{
    return m_ang_resolution;
}




} // namespace dds_


} // namespace msg


} // namespace rover_msgs
// Include auxiliary functions like for serializing/deserializing.
#include "rover_msgsCdrAux.ipp"

