// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file sensor_msgsPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen.
 */


#include <fastdds/rtps/common/CdrSerialization.hpp>

#include "sensor_msgsPubSubTypes.h"
#include "sensor_msgsCdrAux.hpp"

using SerializedPayload_t = eprosima::fastrtps::rtps::SerializedPayload_t;
using InstanceHandle_t = eprosima::fastrtps::rtps::InstanceHandle_t;
using DataRepresentationId_t = eprosima::fastdds::dds::DataRepresentationId_t;

namespace sensor_msgs {
    namespace msg {
        namespace dds_ {


            PointField_PubSubType::PointField_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::PointField_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(PointField_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__PointField__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__PointField__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__PointField__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            PointField_PubSubType::~PointField_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool PointField_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                PointField_* p_type = static_cast<PointField_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool PointField_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    PointField_* p_type = static_cast<PointField_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> PointField_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<PointField_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<PointField_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* PointField_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new PointField_());
            }

            void PointField_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<PointField_*>(data));
            }

            bool PointField_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                PointField_* p_type = static_cast<PointField_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__PointField__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__PointField__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }



            PointCloud2_PubSubType::PointCloud2_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::PointCloud2_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(PointCloud2_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__PointCloud2__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__PointCloud2__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__PointCloud2__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            PointCloud2_PubSubType::~PointCloud2_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool PointCloud2_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                PointCloud2_* p_type = static_cast<PointCloud2_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool PointCloud2_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    PointCloud2_* p_type = static_cast<PointCloud2_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> PointCloud2_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<PointCloud2_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<PointCloud2_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* PointCloud2_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new PointCloud2_());
            }

            void PointCloud2_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<PointCloud2_*>(data));
            }

            bool PointCloud2_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                PointCloud2_* p_type = static_cast<PointCloud2_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__PointCloud2__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__PointCloud2__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }





            ChannelFloat32_PubSubType::ChannelFloat32_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::ChannelFloat32_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(ChannelFloat32_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__ChannelFloat32__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__ChannelFloat32__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__ChannelFloat32__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            ChannelFloat32_PubSubType::~ChannelFloat32_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool ChannelFloat32_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                ChannelFloat32_* p_type = static_cast<ChannelFloat32_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool ChannelFloat32_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    ChannelFloat32_* p_type = static_cast<ChannelFloat32_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> ChannelFloat32_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<ChannelFloat32_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<ChannelFloat32_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* ChannelFloat32_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new ChannelFloat32_());
            }

            void ChannelFloat32_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<ChannelFloat32_*>(data));
            }

            bool ChannelFloat32_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                ChannelFloat32_* p_type = static_cast<ChannelFloat32_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__ChannelFloat32__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__ChannelFloat32__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }



            Point_PubSubType::Point_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::Point_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(Point_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__Point__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__Point__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__Point__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            Point_PubSubType::~Point_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool Point_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                Point_* p_type = static_cast<Point_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool Point_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    Point_* p_type = static_cast<Point_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> Point_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<Point_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<Point_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* Point_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new Point_());
            }

            void Point_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<Point_*>(data));
            }

            bool Point_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                Point_* p_type = static_cast<Point_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__Point__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__Point__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }





            PointCloud_PubSubType::PointCloud_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::PointCloud_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(PointCloud_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__PointCloud__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__PointCloud__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__PointCloud__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            PointCloud_PubSubType::~PointCloud_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool PointCloud_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                PointCloud_* p_type = static_cast<PointCloud_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool PointCloud_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    PointCloud_* p_type = static_cast<PointCloud_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> PointCloud_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<PointCloud_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<PointCloud_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* PointCloud_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new PointCloud_());
            }

            void PointCloud_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<PointCloud_*>(data));
            }

            bool PointCloud_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                PointCloud_* p_type = static_cast<PointCloud_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__PointCloud__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__PointCloud__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }





            LaserScan_PubSubType::LaserScan_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::LaserScan_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(LaserScan_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__LaserScan__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__LaserScan__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__LaserScan__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            LaserScan_PubSubType::~LaserScan_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool LaserScan_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                LaserScan_* p_type = static_cast<LaserScan_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool LaserScan_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    LaserScan_* p_type = static_cast<LaserScan_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> LaserScan_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<LaserScan_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<LaserScan_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* LaserScan_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new LaserScan_());
            }

            void LaserScan_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<LaserScan_*>(data));
            }

            bool LaserScan_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                LaserScan_* p_type = static_cast<LaserScan_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__LaserScan__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__LaserScan__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }





            Image_PubSubType::Image_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::Image_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(Image_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__Image__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__Image__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__Image__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            Image_PubSubType::~Image_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool Image_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                Image_* p_type = static_cast<Image_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool Image_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    Image_* p_type = static_cast<Image_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> Image_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<Image_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<Image_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* Image_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new Image_());
            }

            void Image_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<Image_*>(data));
            }

            bool Image_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                Image_* p_type = static_cast<Image_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__Image__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__Image__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }



            RegionOfInterest_PubSubType::RegionOfInterest_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::RegionOfInterest_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(RegionOfInterest_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__RegionOfInterest__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__RegionOfInterest__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__RegionOfInterest__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            RegionOfInterest_PubSubType::~RegionOfInterest_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool RegionOfInterest_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                RegionOfInterest_* p_type = static_cast<RegionOfInterest_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool RegionOfInterest_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    RegionOfInterest_* p_type = static_cast<RegionOfInterest_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> RegionOfInterest_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<RegionOfInterest_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<RegionOfInterest_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* RegionOfInterest_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new RegionOfInterest_());
            }

            void RegionOfInterest_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<RegionOfInterest_*>(data));
            }

            bool RegionOfInterest_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                RegionOfInterest_* p_type = static_cast<RegionOfInterest_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__RegionOfInterest__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__RegionOfInterest__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }



            CameraInfo_PubSubType::CameraInfo_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::CameraInfo_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(CameraInfo_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__CameraInfo__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__CameraInfo__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__CameraInfo__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            CameraInfo_PubSubType::~CameraInfo_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool CameraInfo_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                CameraInfo_* p_type = static_cast<CameraInfo_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool CameraInfo_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    CameraInfo_* p_type = static_cast<CameraInfo_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> CameraInfo_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<CameraInfo_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<CameraInfo_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* CameraInfo_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new CameraInfo_());
            }

            void CameraInfo_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<CameraInfo_*>(data));
            }

            bool CameraInfo_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                CameraInfo_* p_type = static_cast<CameraInfo_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__CameraInfo__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__CameraInfo__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }





            JointState_PubSubType::JointState_PubSubType()
            {
                setName("sensor_msgs::msg::dds_::JointState_");
                uint32_t type_size =
            #if FASTCDR_VERSION_MAJOR == 1
                    static_cast<uint32_t>(JointState_::getMaxCdrSerializedSize());
            #else
                    sensor_msgs_msg_dds__JointState__max_cdr_typesize;
            #endif
                type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
                m_typeSize = type_size + 4; /*encapsulation*/
                m_isGetKeyDefined = false;
                uint32_t keyLength = sensor_msgs_msg_dds__JointState__max_key_cdr_typesize > 16 ? sensor_msgs_msg_dds__JointState__max_key_cdr_typesize : 16;
                m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
                memset(m_keyBuffer, 0, keyLength);
            }

            JointState_PubSubType::~JointState_PubSubType()
            {
                if (m_keyBuffer != nullptr)
                {
                    free(m_keyBuffer);
                }
            }

            bool JointState_PubSubType::serialize(
                    void* data,
                    SerializedPayload_t* payload,
                    DataRepresentationId_t data_representation)
            {
                JointState_* p_type = static_cast<JointState_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                        data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                        eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
                payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            #if FASTCDR_VERSION_MAJOR > 1
                ser.set_encoding_flag(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                    eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);
            #endif // FASTCDR_VERSION_MAJOR > 1

                try
                {
                    // Serialize encapsulation
                    ser.serialize_encapsulation();
                    // Serialize the object.
                    ser << *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                // Get the serialized length
            #if FASTCDR_VERSION_MAJOR == 1
                payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            #else
                payload->length = static_cast<uint32_t>(ser.get_serialized_data_length());
            #endif // FASTCDR_VERSION_MAJOR == 1
                return true;
            }

            bool JointState_PubSubType::deserialize(
                    SerializedPayload_t* payload,
                    void* data)
            {
                try
                {
                    // Convert DATA to pointer of your type
                    JointState_* p_type = static_cast<JointState_*>(data);

                    // Object that manages the raw buffer.
                    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                    // Object that deserializes the data.
                    eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN
            #if FASTCDR_VERSION_MAJOR == 1
                            , eprosima::fastcdr::Cdr::CdrType::DDS_CDR
            #endif // FASTCDR_VERSION_MAJOR == 1
                            );

                    // Deserialize encapsulation.
                    deser.read_encapsulation();
                    payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                    // Deserialize the object.
                    deser >> *p_type;
                }
                catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                {
                    return false;
                }

                return true;
            }

            std::function<uint32_t()> JointState_PubSubType::getSerializedSizeProvider(
                    void* data,
                    DataRepresentationId_t data_representation)
            {
                return [data, data_representation]() -> uint32_t
                       {
            #if FASTCDR_VERSION_MAJOR == 1
                           static_cast<void>(data_representation);
                           return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<JointState_*>(data))) +
                                  4u /*encapsulation*/;
            #else
                           try
                           {
                               eprosima::fastcdr::CdrSizeCalculator calculator(
                                   data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                                   eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                               size_t current_alignment {0};
                               return static_cast<uint32_t>(calculator.calculate_serialized_size(
                                           *static_cast<JointState_*>(data), current_alignment)) +
                                       4u /*encapsulation*/;
                           }
                           catch (eprosima::fastcdr::exception::Exception& /*exception*/)
                           {
                               return 0;
                           }
            #endif // FASTCDR_VERSION_MAJOR == 1
                       };
            }

            void* JointState_PubSubType::createData()
            {
                return reinterpret_cast<void*>(new JointState_());
            }

            void JointState_PubSubType::deleteData(
                    void* data)
            {
                delete(reinterpret_cast<JointState_*>(data));
            }

            bool JointState_PubSubType::getKey(
                    void* data,
                    InstanceHandle_t* handle,
                    bool force_md5)
            {
                if (!m_isGetKeyDefined)
                {
                    return false;
                }

                JointState_* p_type = static_cast<JointState_*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                        sensor_msgs_msg_dds__JointState__max_key_cdr_typesize);

                // Object that serializes the data.
                eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv1);
            #if FASTCDR_VERSION_MAJOR == 1
                p_type->serializeKey(ser);
            #else
                eprosima::fastcdr::serialize_key(ser, *p_type);
            #endif // FASTCDR_VERSION_MAJOR == 1
                if (force_md5 || sensor_msgs_msg_dds__JointState__max_key_cdr_typesize > 16)
                {
                    m_md5.init();
            #if FASTCDR_VERSION_MAJOR == 1
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
            #else
                    m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
            #endif // FASTCDR_VERSION_MAJOR == 1
                    m_md5.finalize();
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_md5.digest[i];
                    }
                }
                else
                {
                    for (uint8_t i = 0; i < 16; ++i)
                    {
                        handle->value[i] = m_keyBuffer[i];
                    }
                }
                return true;
            }


        } //End of namespace dds_


    } //End of namespace msg


} //End of namespace sensor_msgs

