// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file tf2_msgs.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "tf2_msgs.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace tf2_msgs {

namespace msg {

namespace dds_ {





TFMessage_::TFMessage_()
{
}

TFMessage_::~TFMessage_()
{
}

TFMessage_::TFMessage_(
        const TFMessage_& x)
{
    m_transforms = x.m_transforms;
}

TFMessage_::TFMessage_(
        TFMessage_&& x) noexcept
{
    m_transforms = std::move(x.m_transforms);
}

TFMessage_& TFMessage_::operator =(
        const TFMessage_& x)
{

    m_transforms = x.m_transforms;
    return *this;
}

TFMessage_& TFMessage_::operator =(
        TFMessage_&& x) noexcept
{

    m_transforms = std::move(x.m_transforms);
    return *this;
}

bool TFMessage_::operator ==(
        const TFMessage_& x) const
{
    return (m_transforms == x.m_transforms);
}

bool TFMessage_::operator !=(
        const TFMessage_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member transforms
 * @param _transforms New value to be copied in member transforms
 */
void TFMessage_::transforms(
        const std::vector<geometry_msgs::msg::dds_::TransformStamped_>& _transforms)
{
    m_transforms = _transforms;
}

/*!
 * @brief This function moves the value in member transforms
 * @param _transforms New value to be moved in member transforms
 */
void TFMessage_::transforms(
        std::vector<geometry_msgs::msg::dds_::TransformStamped_>&& _transforms)
{
    m_transforms = std::move(_transforms);
}

/*!
 * @brief This function returns a constant reference to member transforms
 * @return Constant reference to member transforms
 */
const std::vector<geometry_msgs::msg::dds_::TransformStamped_>& TFMessage_::transforms() const
{
    return m_transforms;
}

/*!
 * @brief This function returns a reference to member transforms
 * @return Reference to member transforms
 */
std::vector<geometry_msgs::msg::dds_::TransformStamped_>& TFMessage_::transforms()
{
    return m_transforms;
}




} // namespace dds_


} // namespace msg


} // namespace tf2_msgs
// Include auxiliary functions like for serializing/deserializing.
#include "tf2_msgsCdrAux.ipp"

