// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TaskData.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_TASKDATA_H_
#define _FAST_DDS_GENERATED_TASKDATA_H_


#include <fastdds/utils/md5.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TaskData_SOURCE)
#define TaskData_DllAPI __declspec( dllexport )
#else
#define TaskData_DllAPI __declspec( dllimport )
#endif // TaskData_SOURCE
#else
#define TaskData_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TaskData_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure TaskData defined by the user in the IDL file.
 * @ingroup TASKDATA
 */
class TaskData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TaskData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TaskData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TaskData that will be copied.
     */
    eProsima_user_DllExport TaskData(
            const TaskData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TaskData that will be copied.
     */
    eProsima_user_DllExport TaskData(
            TaskData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TaskData that will be copied.
     */
    eProsima_user_DllExport TaskData& operator =(
            const TaskData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TaskData that will be copied.
     */
    eProsima_user_DllExport TaskData& operator =(
            TaskData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x TaskData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TaskData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x TaskData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TaskData& x) const;

    /*!
     * @brief This function sets a value in member packet_id
     * @param _packet_id New value for member packet_id
     */
    eProsima_user_DllExport void packet_id(
            uint32_t _packet_id);

    /*!
     * @brief This function returns the value of member packet_id
     * @return Value of member packet_id
     */
    eProsima_user_DllExport uint32_t packet_id() const;

    /*!
     * @brief This function returns a reference to member packet_id
     * @return Reference to member packet_id
     */
    eProsima_user_DllExport uint32_t& packet_id();

    /*!
     * @brief This function sets a value in member workload
     * @param _workload New value for member workload
     */
    eProsima_user_DllExport void workload(
            int32_t _workload);

    /*!
     * @brief This function returns the value of member workload
     * @return Value of member workload
     */
    eProsima_user_DllExport int32_t workload() const;

    /*!
     * @brief This function returns a reference to member workload
     * @return Reference to member workload
     */
    eProsima_user_DllExport int32_t& workload();

    /*!
     * @brief This function sets a value in member deadline_missed
     * @param _deadline_missed New value for member deadline_missed
     */
    eProsima_user_DllExport void deadline_missed(
            bool _deadline_missed);

    /*!
     * @brief This function returns the value of member deadline_missed
     * @return Value of member deadline_missed
     */
    eProsima_user_DllExport bool deadline_missed() const;

    /*!
     * @brief This function returns a reference to member deadline_missed
     * @return Reference to member deadline_missed
     */
    eProsima_user_DllExport bool& deadline_missed();

    /*!
     * @brief This function sets a value in member latency_ms
     * @param _latency_ms New value for member latency_ms
     */
    eProsima_user_DllExport void latency_ms(
            float _latency_ms);

    /*!
     * @brief This function returns the value of member latency_ms
     * @return Value of member latency_ms
     */
    eProsima_user_DllExport float latency_ms() const;

    /*!
     * @brief This function returns a reference to member latency_ms
     * @return Reference to member latency_ms
     */
    eProsima_user_DllExport float& latency_ms();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const TaskData& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    uint32_t m_packet_id;
    int32_t m_workload;
    bool m_deadline_missed;
    float m_latency_ms;
};

#endif // _FAST_DDS_GENERATED_TASKDATA_H_
