// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file sensor_msgsCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_DDS__SENSOR_MSGSCDRAUX_HPP_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_DDS__SENSOR_MSGSCDRAUX_HPP_

#include "sensor_msgs.h"

constexpr uint32_t sensor_msgs_msg_dds__Point__max_cdr_typesize {16UL};
constexpr uint32_t sensor_msgs_msg_dds__Point__max_key_cdr_typesize {0UL};


constexpr uint32_t sensor_msgs_msg_dds__PointCloud__max_cdr_typesize {68696UL};
constexpr uint32_t sensor_msgs_msg_dds__PointCloud__max_key_cdr_typesize {0UL};




constexpr uint32_t sensor_msgs_msg_dds__ChannelFloat32__max_cdr_typesize {668UL};
constexpr uint32_t sensor_msgs_msg_dds__ChannelFloat32__max_key_cdr_typesize {0UL};




constexpr uint32_t sensor_msgs_msg_dds__LaserScan__max_cdr_typesize {1116UL};
constexpr uint32_t sensor_msgs_msg_dds__LaserScan__max_key_cdr_typesize {0UL};

constexpr uint32_t sensor_msgs_msg_dds__RegionOfInterest__max_cdr_typesize {21UL};
constexpr uint32_t sensor_msgs_msg_dds__RegionOfInterest__max_key_cdr_typesize {0UL};


constexpr uint32_t sensor_msgs_msg_dds__PointCloud2__max_cdr_typesize {28013UL};
constexpr uint32_t sensor_msgs_msg_dds__PointCloud2__max_key_cdr_typesize {0UL};




constexpr uint32_t sensor_msgs_msg_dds__CameraInfo__max_cdr_typesize {1621UL};
constexpr uint32_t sensor_msgs_msg_dds__CameraInfo__max_key_cdr_typesize {0UL};




constexpr uint32_t sensor_msgs_msg_dds__PointField__max_cdr_typesize {276UL};
constexpr uint32_t sensor_msgs_msg_dds__PointField__max_key_cdr_typesize {0UL};

constexpr uint32_t sensor_msgs_msg_dds__Image__max_cdr_typesize {660UL};
constexpr uint32_t sensor_msgs_msg_dds__Image__max_key_cdr_typesize {0UL};


constexpr uint32_t sensor_msgs_msg_dds__JointState__max_cdr_typesize {28712UL};
constexpr uint32_t sensor_msgs_msg_dds__JointState__max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::PointField_& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::PointCloud2_& data);





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::ChannelFloat32_& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::Point_& data);





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::PointCloud_& data);





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::LaserScan_& data);





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::Image_& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::RegionOfInterest_& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::CameraInfo_& data);





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const sensor_msgs::msg::dds_::JointState_& data);





} // namespace fastcdr
} // namespace eprosima

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_DDS__SENSOR_MSGSCDRAUX_HPP_

