// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Telemetry.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__TELEMETRY_HPP
#define FAST_DDS_GENERATED__TELEMETRY_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TELEMETRY_SOURCE)
#define TELEMETRY_DllAPI __declspec( dllexport )
#else
#define TELEMETRY_DllAPI __declspec( dllimport )
#endif // TELEMETRY_SOURCE
#else
#define TELEMETRY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TELEMETRY_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure SystemStats defined by the user in the IDL file.
 * @ingroup Telemetry
 */
class SystemStats
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SystemStats()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SystemStats()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats(
            const SystemStats& x)
    {
                    m_packet_id = x.m_packet_id;

                    m_roll = x.m_roll;

                    m_pitch = x.m_pitch;

                    m_yaw = x.m_yaw;

                    m_altitude = x.m_altitude;

                    m_latency_us = x.m_latency_us;

                    m_speed = x.m_speed;

                    m_deadline_missed = x.m_deadline_missed;

                    m_status_msg = x.m_status_msg;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats(
            SystemStats&& x) noexcept
    {
        m_packet_id = x.m_packet_id;
        m_roll = x.m_roll;
        m_pitch = x.m_pitch;
        m_yaw = x.m_yaw;
        m_altitude = x.m_altitude;
        m_latency_us = x.m_latency_us;
        m_speed = x.m_speed;
        m_deadline_missed = x.m_deadline_missed;
        m_status_msg = std::move(x.m_status_msg);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats& operator =(
            const SystemStats& x)
    {

                    m_packet_id = x.m_packet_id;

                    m_roll = x.m_roll;

                    m_pitch = x.m_pitch;

                    m_yaw = x.m_yaw;

                    m_altitude = x.m_altitude;

                    m_latency_us = x.m_latency_us;

                    m_speed = x.m_speed;

                    m_deadline_missed = x.m_deadline_missed;

                    m_status_msg = x.m_status_msg;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats& operator =(
            SystemStats&& x) noexcept
    {

        m_packet_id = x.m_packet_id;
        m_roll = x.m_roll;
        m_pitch = x.m_pitch;
        m_yaw = x.m_yaw;
        m_altitude = x.m_altitude;
        m_latency_us = x.m_latency_us;
        m_speed = x.m_speed;
        m_deadline_missed = x.m_deadline_missed;
        m_status_msg = std::move(x.m_status_msg);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SystemStats object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SystemStats& x) const
    {
        return (m_packet_id == x.m_packet_id &&
           m_roll == x.m_roll &&
           m_pitch == x.m_pitch &&
           m_yaw == x.m_yaw &&
           m_altitude == x.m_altitude &&
           m_latency_us == x.m_latency_us &&
           m_speed == x.m_speed &&
           m_deadline_missed == x.m_deadline_missed &&
           m_status_msg == x.m_status_msg);
    }

    /*!
     * @brief Comparison operator.
     * @param x SystemStats object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SystemStats& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member packet_id
     * @param _packet_id New value for member packet_id
     */
    eProsima_user_DllExport void packet_id(
            uint32_t _packet_id)
    {
        m_packet_id = _packet_id;
    }

    /*!
     * @brief This function returns the value of member packet_id
     * @return Value of member packet_id
     */
    eProsima_user_DllExport uint32_t packet_id() const
    {
        return m_packet_id;
    }

    /*!
     * @brief This function returns a reference to member packet_id
     * @return Reference to member packet_id
     */
    eProsima_user_DllExport uint32_t& packet_id()
    {
        return m_packet_id;
    }


    /*!
     * @brief This function sets a value in member roll
     * @param _roll New value for member roll
     */
    eProsima_user_DllExport void roll(
            float _roll)
    {
        m_roll = _roll;
    }

    /*!
     * @brief This function returns the value of member roll
     * @return Value of member roll
     */
    eProsima_user_DllExport float roll() const
    {
        return m_roll;
    }

    /*!
     * @brief This function returns a reference to member roll
     * @return Reference to member roll
     */
    eProsima_user_DllExport float& roll()
    {
        return m_roll;
    }


    /*!
     * @brief This function sets a value in member pitch
     * @param _pitch New value for member pitch
     */
    eProsima_user_DllExport void pitch(
            float _pitch)
    {
        m_pitch = _pitch;
    }

    /*!
     * @brief This function returns the value of member pitch
     * @return Value of member pitch
     */
    eProsima_user_DllExport float pitch() const
    {
        return m_pitch;
    }

    /*!
     * @brief This function returns a reference to member pitch
     * @return Reference to member pitch
     */
    eProsima_user_DllExport float& pitch()
    {
        return m_pitch;
    }


    /*!
     * @brief This function sets a value in member yaw
     * @param _yaw New value for member yaw
     */
    eProsima_user_DllExport void yaw(
            float _yaw)
    {
        m_yaw = _yaw;
    }

    /*!
     * @brief This function returns the value of member yaw
     * @return Value of member yaw
     */
    eProsima_user_DllExport float yaw() const
    {
        return m_yaw;
    }

    /*!
     * @brief This function returns a reference to member yaw
     * @return Reference to member yaw
     */
    eProsima_user_DllExport float& yaw()
    {
        return m_yaw;
    }


    /*!
     * @brief This function sets a value in member altitude
     * @param _altitude New value for member altitude
     */
    eProsima_user_DllExport void altitude(
            float _altitude)
    {
        m_altitude = _altitude;
    }

    /*!
     * @brief This function returns the value of member altitude
     * @return Value of member altitude
     */
    eProsima_user_DllExport float altitude() const
    {
        return m_altitude;
    }

    /*!
     * @brief This function returns a reference to member altitude
     * @return Reference to member altitude
     */
    eProsima_user_DllExport float& altitude()
    {
        return m_altitude;
    }


    /*!
     * @brief This function sets a value in member latency_us
     * @param _latency_us New value for member latency_us
     */
    eProsima_user_DllExport void latency_us(
            float _latency_us)
    {
        m_latency_us = _latency_us;
    }

    /*!
     * @brief This function returns the value of member latency_us
     * @return Value of member latency_us
     */
    eProsima_user_DllExport float latency_us() const
    {
        return m_latency_us;
    }

    /*!
     * @brief This function returns a reference to member latency_us
     * @return Reference to member latency_us
     */
    eProsima_user_DllExport float& latency_us()
    {
        return m_latency_us;
    }


    /*!
     * @brief This function sets a value in member speed
     * @param _speed New value for member speed
     */
    eProsima_user_DllExport void speed(
            float _speed)
    {
        m_speed = _speed;
    }

    /*!
     * @brief This function returns the value of member speed
     * @return Value of member speed
     */
    eProsima_user_DllExport float speed() const
    {
        return m_speed;
    }

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport float& speed()
    {
        return m_speed;
    }


    /*!
     * @brief This function sets a value in member deadline_missed
     * @param _deadline_missed New value for member deadline_missed
     */
    eProsima_user_DllExport void deadline_missed(
            bool _deadline_missed)
    {
        m_deadline_missed = _deadline_missed;
    }

    /*!
     * @brief This function returns the value of member deadline_missed
     * @return Value of member deadline_missed
     */
    eProsima_user_DllExport bool deadline_missed() const
    {
        return m_deadline_missed;
    }

    /*!
     * @brief This function returns a reference to member deadline_missed
     * @return Reference to member deadline_missed
     */
    eProsima_user_DllExport bool& deadline_missed()
    {
        return m_deadline_missed;
    }


    /*!
     * @brief This function copies the value in member status_msg
     * @param _status_msg New value to be copied in member status_msg
     */
    eProsima_user_DllExport void status_msg(
            const eprosima::fastcdr::fixed_string<32>& _status_msg)
    {
        m_status_msg = _status_msg;
    }

    /*!
     * @brief This function moves the value in member status_msg
     * @param _status_msg New value to be moved in member status_msg
     */
    eProsima_user_DllExport void status_msg(
            eprosima::fastcdr::fixed_string<32>&& _status_msg)
    {
        m_status_msg = std::move(_status_msg);
    }

    /*!
     * @brief This function returns a constant reference to member status_msg
     * @return Constant reference to member status_msg
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<32>& status_msg() const
    {
        return m_status_msg;
    }

    /*!
     * @brief This function returns a reference to member status_msg
     * @return Reference to member status_msg
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<32>& status_msg()
    {
        return m_status_msg;
    }



private:

    uint32_t m_packet_id{0};
    float m_roll{0.0};
    float m_pitch{0.0};
    float m_yaw{0.0};
    float m_altitude{0.0};
    float m_latency_us{0.0};
    float m_speed{0.0};
    bool m_deadline_missed{false};
    eprosima::fastcdr::fixed_string<32> m_status_msg;

};

#endif // _FAST_DDS_GENERATED_TELEMETRY_HPP_






