// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file student_msgs.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_STUDENT_MSGS_H_
#define _FAST_DDS_GENERATED_STUDENT_MSGS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(STUDENT_MSGS_SOURCE)
#define STUDENT_MSGS_DllAPI __declspec( dllexport )
#else
#define STUDENT_MSGS_DllAPI __declspec( dllimport )
#endif // STUDENT_MSGS_SOURCE
#else
#define STUDENT_MSGS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define STUDENT_MSGS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure Student defined by the user in the IDL file.
 * @ingroup student_msgs
 */
class Student
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Student();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Student();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Student that will be copied.
     */
    eProsima_user_DllExport Student(
            const Student& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Student that will be copied.
     */
    eProsima_user_DllExport Student(
            Student&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Student that will be copied.
     */
    eProsima_user_DllExport Student& operator =(
            const Student& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Student that will be copied.
     */
    eProsima_user_DllExport Student& operator =(
            Student&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Student object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Student& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Student object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Student& x) const;

    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name);

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name);

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const;

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name();


    /*!
     * @brief This function copies the value in member surname
     * @param _surname New value to be copied in member surname
     */
    eProsima_user_DllExport void surname(
            const std::string& _surname);

    /*!
     * @brief This function moves the value in member surname
     * @param _surname New value to be moved in member surname
     */
    eProsima_user_DllExport void surname(
            std::string&& _surname);

    /*!
     * @brief This function returns a constant reference to member surname
     * @return Constant reference to member surname
     */
    eProsima_user_DllExport const std::string& surname() const;

    /*!
     * @brief This function returns a reference to member surname
     * @return Reference to member surname
     */
    eProsima_user_DllExport std::string& surname();


    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            int32_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport int32_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport int32_t& id();

private:

    std::string m_name;
    std::string m_surname;
    int32_t m_id{0};

};

#endif // _FAST_DDS_GENERATED_STUDENT_MSGS_H_



