// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file thread_msgs.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_THREAD_MSGS_H_
#define _FAST_DDS_GENERATED_THREAD_MSGS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(THREAD_MSGS_SOURCE)
#define THREAD_MSGS_DllAPI __declspec( dllexport )
#else
#define THREAD_MSGS_DllAPI __declspec( dllimport )
#endif // THREAD_MSGS_SOURCE
#else
#define THREAD_MSGS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define THREAD_MSGS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure ThreadEvent defined by the user in the IDL file.
 * @ingroup thread_msgs
 */
class ThreadEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ThreadEvent();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ThreadEvent();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ThreadEvent that will be copied.
     */
    eProsima_user_DllExport ThreadEvent(
            const ThreadEvent& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ThreadEvent that will be copied.
     */
    eProsima_user_DllExport ThreadEvent(
            ThreadEvent&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ThreadEvent that will be copied.
     */
    eProsima_user_DllExport ThreadEvent& operator =(
            const ThreadEvent& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ThreadEvent that will be copied.
     */
    eProsima_user_DllExport ThreadEvent& operator =(
            ThreadEvent&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x ThreadEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ThreadEvent& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ThreadEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ThreadEvent& x) const;

    /*!
     * @brief This function copies the value in member task_name
     * @param _task_name New value to be copied in member task_name
     */
    eProsima_user_DllExport void task_name(
            const std::string& _task_name);

    /*!
     * @brief This function moves the value in member task_name
     * @param _task_name New value to be moved in member task_name
     */
    eProsima_user_DllExport void task_name(
            std::string&& _task_name);

    /*!
     * @brief This function returns a constant reference to member task_name
     * @return Constant reference to member task_name
     */
    eProsima_user_DllExport const std::string& task_name() const;

    /*!
     * @brief This function returns a reference to member task_name
     * @return Reference to member task_name
     */
    eProsima_user_DllExport std::string& task_name();


    /*!
     * @brief This function sets a value in member thread_id
     * @param _thread_id New value for member thread_id
     */
    eProsima_user_DllExport void thread_id(
            int32_t _thread_id);

    /*!
     * @brief This function returns the value of member thread_id
     * @return Value of member thread_id
     */
    eProsima_user_DllExport int32_t thread_id() const;

    /*!
     * @brief This function returns a reference to member thread_id
     * @return Reference to member thread_id
     */
    eProsima_user_DllExport int32_t& thread_id();


    /*!
     * @brief This function sets a value in member start_time_ms
     * @param _start_time_ms New value for member start_time_ms
     */
    eProsima_user_DllExport void start_time_ms(
            double _start_time_ms);

    /*!
     * @brief This function returns the value of member start_time_ms
     * @return Value of member start_time_ms
     */
    eProsima_user_DllExport double start_time_ms() const;

    /*!
     * @brief This function returns a reference to member start_time_ms
     * @return Reference to member start_time_ms
     */
    eProsima_user_DllExport double& start_time_ms();


    /*!
     * @brief This function sets a value in member end_time_ms
     * @param _end_time_ms New value for member end_time_ms
     */
    eProsima_user_DllExport void end_time_ms(
            double _end_time_ms);

    /*!
     * @brief This function returns the value of member end_time_ms
     * @return Value of member end_time_ms
     */
    eProsima_user_DllExport double end_time_ms() const;

    /*!
     * @brief This function returns a reference to member end_time_ms
     * @return Reference to member end_time_ms
     */
    eProsima_user_DllExport double& end_time_ms();


    /*!
     * @brief This function sets a value in member cost_ms
     * @param _cost_ms New value for member cost_ms
     */
    eProsima_user_DllExport void cost_ms(
            double _cost_ms);

    /*!
     * @brief This function returns the value of member cost_ms
     * @return Value of member cost_ms
     */
    eProsima_user_DllExport double cost_ms() const;

    /*!
     * @brief This function returns a reference to member cost_ms
     * @return Reference to member cost_ms
     */
    eProsima_user_DllExport double& cost_ms();


    /*!
     * @brief This function sets a value in member period_ms
     * @param _period_ms New value for member period_ms
     */
    eProsima_user_DllExport void period_ms(
            int32_t _period_ms);

    /*!
     * @brief This function returns the value of member period_ms
     * @return Value of member period_ms
     */
    eProsima_user_DllExport int32_t period_ms() const;

    /*!
     * @brief This function returns a reference to member period_ms
     * @return Reference to member period_ms
     */
    eProsima_user_DllExport int32_t& period_ms();


    /*!
     * @brief This function sets a value in member missed_deadline
     * @param _missed_deadline New value for member missed_deadline
     */
    eProsima_user_DllExport void missed_deadline(
            bool _missed_deadline);

    /*!
     * @brief This function returns the value of member missed_deadline
     * @return Value of member missed_deadline
     */
    eProsima_user_DllExport bool missed_deadline() const;

    /*!
     * @brief This function returns a reference to member missed_deadline
     * @return Reference to member missed_deadline
     */
    eProsima_user_DllExport bool& missed_deadline();

private:

    std::string m_task_name;
    int32_t m_thread_id{0};
    double m_start_time_ms{0.0};
    double m_end_time_ms{0.0};
    double m_cost_ms{0.0};
    int32_t m_period_ms{0};
    bool m_missed_deadline{false};

};

#endif // _FAST_DDS_GENERATED_THREAD_MSGS_H_



