// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file service_msgsTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "service_msgsTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "service_msgs.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Request_type_identifier(
        TypeIdentifierPair& type_ids_Request)
{

    ReturnCode_t return_code_Request {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Request =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Request", type_ids_Request);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Request)
    {
        StructTypeFlag struct_flags_Request = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Request = "Request";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Request;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Request;
        CompleteTypeDetail detail_Request = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Request, ann_custom_Request, type_name_Request.to_string());
        CompleteStructHeader header_Request;
        header_Request = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Request);
        CompleteStructMemberSeq member_seq_Request;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_Request.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_Request);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_Request, member_id);
        }
        {
            TypeIdentifierPair type_ids_operation;
            ReturnCode_t return_code_operation {eprosima::fastdds::dds::RETCODE_OK};
            return_code_operation =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_operation);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_operation)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_operation))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_operation = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_operation = 0x00000001;
            bool common_operation_ec {false};
            CommonStructMember common_operation {TypeObjectUtils::build_common_struct_member(member_id_operation, member_flags_operation, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_operation, common_operation_ec))};
            if (!common_operation_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure operation member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_operation = "operation";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_operation;
            ann_custom_Request.reset();
            CompleteMemberDetail detail_operation = TypeObjectUtils::build_complete_member_detail(name_operation, member_ann_builtin_operation, ann_custom_Request);
            CompleteStructMember member_operation = TypeObjectUtils::build_complete_struct_member(common_operation, detail_operation);
            TypeObjectUtils::add_complete_struct_member(member_seq_Request, member_operation);
        }
        {
            TypeIdentifierPair type_ids_data_a;
            ReturnCode_t return_code_data_a {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data_a =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_data_a);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data_a)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "data_a Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_data_a = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data_a = 0x00000002;
            bool common_data_a_ec {false};
            CommonStructMember common_data_a {TypeObjectUtils::build_common_struct_member(member_id_data_a, member_flags_data_a, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data_a, common_data_a_ec))};
            if (!common_data_a_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data_a member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data_a = "data_a";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data_a;
            ann_custom_Request.reset();
            CompleteMemberDetail detail_data_a = TypeObjectUtils::build_complete_member_detail(name_data_a, member_ann_builtin_data_a, ann_custom_Request);
            CompleteStructMember member_data_a = TypeObjectUtils::build_complete_struct_member(common_data_a, detail_data_a);
            TypeObjectUtils::add_complete_struct_member(member_seq_Request, member_data_a);
        }
        {
            TypeIdentifierPair type_ids_data_b;
            ReturnCode_t return_code_data_b {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data_b =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_data_b);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data_b)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "data_b Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_data_b = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data_b = 0x00000003;
            bool common_data_b_ec {false};
            CommonStructMember common_data_b {TypeObjectUtils::build_common_struct_member(member_id_data_b, member_flags_data_b, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data_b, common_data_b_ec))};
            if (!common_data_b_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data_b member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data_b = "data_b";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data_b;
            ann_custom_Request.reset();
            CompleteMemberDetail detail_data_b = TypeObjectUtils::build_complete_member_detail(name_data_b, member_ann_builtin_data_b, ann_custom_Request);
            CompleteStructMember member_data_b = TypeObjectUtils::build_complete_struct_member(common_data_b, detail_data_b);
            TypeObjectUtils::add_complete_struct_member(member_seq_Request, member_data_b);
        }
        CompleteStructType struct_type_Request = TypeObjectUtils::build_complete_struct_type(struct_flags_Request, header_Request, member_seq_Request);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Request, type_name_Request.to_string(), type_ids_Request))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Request already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Reply_type_identifier(
        TypeIdentifierPair& type_ids_Reply)
{

    ReturnCode_t return_code_Reply {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Reply =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Reply", type_ids_Reply);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Reply)
    {
        StructTypeFlag struct_flags_Reply = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Reply = "Reply";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Reply;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Reply;
        CompleteTypeDetail detail_Reply = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Reply, ann_custom_Reply, type_name_Reply.to_string());
        CompleteStructHeader header_Reply;
        header_Reply = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Reply);
        CompleteStructMemberSeq member_seq_Reply;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_Reply.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_Reply);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_Reply, member_id);
        }
        {
            TypeIdentifierPair type_ids_correct;
            ReturnCode_t return_code_correct {eprosima::fastdds::dds::RETCODE_OK};
            return_code_correct =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_correct);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_correct)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "correct Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_correct = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_correct = 0x00000001;
            bool common_correct_ec {false};
            CommonStructMember common_correct {TypeObjectUtils::build_common_struct_member(member_id_correct, member_flags_correct, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_correct, common_correct_ec))};
            if (!common_correct_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure correct member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_correct = "correct";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_correct;
            ann_custom_Reply.reset();
            CompleteMemberDetail detail_correct = TypeObjectUtils::build_complete_member_detail(name_correct, member_ann_builtin_correct, ann_custom_Reply);
            CompleteStructMember member_correct = TypeObjectUtils::build_complete_struct_member(common_correct, detail_correct);
            TypeObjectUtils::add_complete_struct_member(member_seq_Reply, member_correct);
        }
        {
            TypeIdentifierPair type_ids_result;
            ReturnCode_t return_code_result {eprosima::fastdds::dds::RETCODE_OK};
            return_code_result =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_result);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_result)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "result Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_result = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_result = 0x00000002;
            bool common_result_ec {false};
            CommonStructMember common_result {TypeObjectUtils::build_common_struct_member(member_id_result, member_flags_result, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_result, common_result_ec))};
            if (!common_result_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure result member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_result = "result";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_result;
            ann_custom_Reply.reset();
            CompleteMemberDetail detail_result = TypeObjectUtils::build_complete_member_detail(name_result, member_ann_builtin_result, ann_custom_Reply);
            CompleteStructMember member_result = TypeObjectUtils::build_complete_struct_member(common_result, detail_result);
            TypeObjectUtils::add_complete_struct_member(member_seq_Reply, member_result);
        }
        CompleteStructType struct_type_Reply = TypeObjectUtils::build_complete_struct_type(struct_flags_Reply, header_Reply, member_seq_Reply);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Reply, type_name_Reply.to_string(), type_ids_Reply))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Reply already registered in TypeObjectRegistry for a different type.");
        }
    }
}
