// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file thread_msgsTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "thread_msgsTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "thread_msgs.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ThreadEvent_type_identifier(
        TypeIdentifierPair& type_ids_ThreadEvent)
{

    ReturnCode_t return_code_ThreadEvent {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ThreadEvent =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "ThreadEvent", type_ids_ThreadEvent);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ThreadEvent)
    {
        StructTypeFlag struct_flags_ThreadEvent = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_ThreadEvent = "ThreadEvent";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ThreadEvent;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ThreadEvent;
        CompleteTypeDetail detail_ThreadEvent = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ThreadEvent, ann_custom_ThreadEvent, type_name_ThreadEvent.to_string());
        CompleteStructHeader header_ThreadEvent;
        header_ThreadEvent = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ThreadEvent);
        CompleteStructMemberSeq member_seq_ThreadEvent;
        {
            TypeIdentifierPair type_ids_task_name;
            ReturnCode_t return_code_task_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_task_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_task_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_task_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_task_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_task_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_task_name = 0x00000000;
            bool common_task_name_ec {false};
            CommonStructMember common_task_name {TypeObjectUtils::build_common_struct_member(member_id_task_name, member_flags_task_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_task_name, common_task_name_ec))};
            if (!common_task_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure task_name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_task_name = "task_name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_task_name;
            ann_custom_ThreadEvent.reset();
            CompleteMemberDetail detail_task_name = TypeObjectUtils::build_complete_member_detail(name_task_name, member_ann_builtin_task_name, ann_custom_ThreadEvent);
            CompleteStructMember member_task_name = TypeObjectUtils::build_complete_struct_member(common_task_name, detail_task_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThreadEvent, member_task_name);
        }
        {
            TypeIdentifierPair type_ids_thread_id;
            ReturnCode_t return_code_thread_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_thread_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_thread_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_thread_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "thread_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_thread_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_thread_id = 0x00000001;
            bool common_thread_id_ec {false};
            CommonStructMember common_thread_id {TypeObjectUtils::build_common_struct_member(member_id_thread_id, member_flags_thread_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_thread_id, common_thread_id_ec))};
            if (!common_thread_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure thread_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_thread_id = "thread_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_thread_id;
            ann_custom_ThreadEvent.reset();
            CompleteMemberDetail detail_thread_id = TypeObjectUtils::build_complete_member_detail(name_thread_id, member_ann_builtin_thread_id, ann_custom_ThreadEvent);
            CompleteStructMember member_thread_id = TypeObjectUtils::build_complete_struct_member(common_thread_id, detail_thread_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThreadEvent, member_thread_id);
        }
        {
            TypeIdentifierPair type_ids_start_time_ms;
            ReturnCode_t return_code_start_time_ms {eprosima::fastdds::dds::RETCODE_OK};
            return_code_start_time_ms =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_start_time_ms);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_start_time_ms)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "start_time_ms Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_start_time_ms = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_start_time_ms = 0x00000002;
            bool common_start_time_ms_ec {false};
            CommonStructMember common_start_time_ms {TypeObjectUtils::build_common_struct_member(member_id_start_time_ms, member_flags_start_time_ms, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_start_time_ms, common_start_time_ms_ec))};
            if (!common_start_time_ms_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure start_time_ms member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_start_time_ms = "start_time_ms";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_start_time_ms;
            ann_custom_ThreadEvent.reset();
            CompleteMemberDetail detail_start_time_ms = TypeObjectUtils::build_complete_member_detail(name_start_time_ms, member_ann_builtin_start_time_ms, ann_custom_ThreadEvent);
            CompleteStructMember member_start_time_ms = TypeObjectUtils::build_complete_struct_member(common_start_time_ms, detail_start_time_ms);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThreadEvent, member_start_time_ms);
        }
        {
            TypeIdentifierPair type_ids_end_time_ms;
            ReturnCode_t return_code_end_time_ms {eprosima::fastdds::dds::RETCODE_OK};
            return_code_end_time_ms =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_end_time_ms);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_end_time_ms)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "end_time_ms Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_end_time_ms = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_end_time_ms = 0x00000003;
            bool common_end_time_ms_ec {false};
            CommonStructMember common_end_time_ms {TypeObjectUtils::build_common_struct_member(member_id_end_time_ms, member_flags_end_time_ms, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_end_time_ms, common_end_time_ms_ec))};
            if (!common_end_time_ms_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure end_time_ms member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_end_time_ms = "end_time_ms";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_end_time_ms;
            ann_custom_ThreadEvent.reset();
            CompleteMemberDetail detail_end_time_ms = TypeObjectUtils::build_complete_member_detail(name_end_time_ms, member_ann_builtin_end_time_ms, ann_custom_ThreadEvent);
            CompleteStructMember member_end_time_ms = TypeObjectUtils::build_complete_struct_member(common_end_time_ms, detail_end_time_ms);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThreadEvent, member_end_time_ms);
        }
        {
            TypeIdentifierPair type_ids_cost_ms;
            ReturnCode_t return_code_cost_ms {eprosima::fastdds::dds::RETCODE_OK};
            return_code_cost_ms =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_cost_ms);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_cost_ms)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "cost_ms Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_cost_ms = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_cost_ms = 0x00000004;
            bool common_cost_ms_ec {false};
            CommonStructMember common_cost_ms {TypeObjectUtils::build_common_struct_member(member_id_cost_ms, member_flags_cost_ms, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_cost_ms, common_cost_ms_ec))};
            if (!common_cost_ms_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure cost_ms member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_cost_ms = "cost_ms";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_cost_ms;
            ann_custom_ThreadEvent.reset();
            CompleteMemberDetail detail_cost_ms = TypeObjectUtils::build_complete_member_detail(name_cost_ms, member_ann_builtin_cost_ms, ann_custom_ThreadEvent);
            CompleteStructMember member_cost_ms = TypeObjectUtils::build_complete_struct_member(common_cost_ms, detail_cost_ms);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThreadEvent, member_cost_ms);
        }
        {
            TypeIdentifierPair type_ids_period_ms;
            ReturnCode_t return_code_period_ms {eprosima::fastdds::dds::RETCODE_OK};
            return_code_period_ms =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_period_ms);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_period_ms)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "period_ms Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_period_ms = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_period_ms = 0x00000005;
            bool common_period_ms_ec {false};
            CommonStructMember common_period_ms {TypeObjectUtils::build_common_struct_member(member_id_period_ms, member_flags_period_ms, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_period_ms, common_period_ms_ec))};
            if (!common_period_ms_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure period_ms member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_period_ms = "period_ms";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_period_ms;
            ann_custom_ThreadEvent.reset();
            CompleteMemberDetail detail_period_ms = TypeObjectUtils::build_complete_member_detail(name_period_ms, member_ann_builtin_period_ms, ann_custom_ThreadEvent);
            CompleteStructMember member_period_ms = TypeObjectUtils::build_complete_struct_member(common_period_ms, detail_period_ms);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThreadEvent, member_period_ms);
        }
        {
            TypeIdentifierPair type_ids_missed_deadline;
            ReturnCode_t return_code_missed_deadline {eprosima::fastdds::dds::RETCODE_OK};
            return_code_missed_deadline =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_missed_deadline);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_missed_deadline)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "missed_deadline Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_missed_deadline = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_missed_deadline = 0x00000006;
            bool common_missed_deadline_ec {false};
            CommonStructMember common_missed_deadline {TypeObjectUtils::build_common_struct_member(member_id_missed_deadline, member_flags_missed_deadline, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_missed_deadline, common_missed_deadline_ec))};
            if (!common_missed_deadline_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure missed_deadline member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_missed_deadline = "missed_deadline";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_missed_deadline;
            ann_custom_ThreadEvent.reset();
            CompleteMemberDetail detail_missed_deadline = TypeObjectUtils::build_complete_member_detail(name_missed_deadline, member_ann_builtin_missed_deadline, ann_custom_ThreadEvent);
            CompleteStructMember member_missed_deadline = TypeObjectUtils::build_complete_struct_member(common_missed_deadline, detail_missed_deadline);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThreadEvent, member_missed_deadline);
        }
        CompleteStructType struct_type_ThreadEvent = TypeObjectUtils::build_complete_struct_type(struct_flags_ThreadEvent, header_ThreadEvent, member_seq_ThreadEvent);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ThreadEvent, type_name_ThreadEvent.to_string(), type_ids_ThreadEvent))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "ThreadEvent already registered in TypeObjectRegistry for a different type.");
        }
    }
}
