#ifndef __sensor_msgs__msg__idl 
#define __sensor_msgs__msg__idl 

#include "geometry_msgs.idl"
#include "std_msgs.idl"


// sensor_msgs verificare se è possibile fare degli include per Header

    module sensor_msgs{
        module msg{
            module dds_{

                //Primo approccio inserisco Time e Header in questo namespace
                // struct TimeStandard{ 
                //     long sec; 
                //     unsigned long nanosec; 
                // }; 

                // struct HeaderStandard{
                //     TimeStandard stamp;             //Two-integer timestamp that is expressed as:
                //                                 // * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
                //                                 // * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
                //                                 // time-handling sugar is provided by the client library
                //     string frame_id;        // Frame this data is associated with
                // };

                //Non presente nei messaggi sensor_msgs di ROS - Già definito in geometry_msgs
                // Da ROS consigliabile utilizzare dove possibile Point invece di Point32_
                
                // struct Point_{
                //     double x;
                //     double y;
                // };

                // Non presete in STRESA, controllare il tipo float e double se vanno bene per questo messaggio
                // struct ChannelFloat32_{
                //     string name;                    // The channel name should give semantics of the channel (e.g.
                //                                         // "intensity" instead of "value").
                //     sequence<float> values;         // The values array should be 1-1 with the elements of the associated
                //                                         // PointCloud.
                // };

                //Rispetto a STRESA cambia la presenza di Header e l'assenza di time_increment, già presente in LaserScan
                // Qui c'è da testare anche la struttura Point proveniente da geometry_msgs
                // struct PointCloud_{
                //     ros::std_msgs::msg::HeaderStandard header;                              // Time of sensor data acquisition, coordinate frame ID.
                //     sequence<ros::geometry_msgs::msg::dds_::Point_> points;                    // Array of 3d points. Each Point32 should be interpreted as a 3d point
                //                                                     // in the frame given in the header.
                //     sequence<ChannelFloat32_> channels;         // Each channel should have the same number of elements as points array,
                //                                                     // and the data in each channel should correspond 1:1 with each point.
                //                                                     // Channel names in common practice are listed in ChannelFloat32.msg.
                // };
                



                /*  Da valutare l'inseriento dei messaggi 

                const octet PointField__INT8 = 1; 
                const octet PointField__UINT8 = 2; 
                const octet PointField__INT16 = 3; 
                const octet PointField__UINT16 = 4; 
                const octet PointField__INT32 = 5; 
                const octet PointField__UINT32 = 6; 
                const octet PointField__FLOAT32 = 7; 
                const octet PointField__FLOAT64 = 8; 

                */
                struct PointField_ { 
                    // Provo a inserire le costanti nel messaggio

                    string name; 
                    unsigned long offset; 
                    octet datatype; 
                    unsigned long count; 
                }; 

                /*
                    Da testare POintCloud2_
                */


                struct PointCloud2_{
                    std_msgs::msg::HeaderStandard header;                              
                    unsigned long height; 
                    unsigned long width; 
                    sequence<sensor_msgs::msg::dds_::PointField_> fields; 
                    boolean is_bigendian; 
                    unsigned long point_step; 
                    unsigned long row_step; 
                    sequence<octet> data; 
                    boolean is_dense;                                                                                                                   
                };
                
                /*
                    Funzionante
                */
                struct ChannelFloat32_{
                    string name;
                    sequence<float> values;                                                                                                                  
                };

                /*
                    Soluzione temporanea, altrimenti 
                    durante il compile del componte 
                    ho undefined reference (SISTEMARE) 
                */
                    struct Point_{
                        float x;
                        float y;
                        float z;
                    };

                // typedef geometry::msg::dds_::Point_* ptr_point;
                /*
                    Funzionante
                */ 
                // __geometry_msgs__msg__idl__Point_ point;
                // geometry_msgs::msg::dds_::Point_ point;
                struct PointCloud_{
                    std_msgs::msg::HeaderStandard header;
                   sequence<Point_> points;
                    sequence<sensor_msgs::msg::dds_::ChannelFloat32_> channels;                                                                                                                  
                };
                /*
                    Funzionante
                */
                struct LaserScan_{
                    std_msgs::msg::HeaderStandard header;
                    float angle_min;                // start angle of the scan [rad]
                    float angle_max;                // end angle of the scan [rad]
                    float angle_increment;          // angular distance between measurements [rad]
                    float time_increment;           // time between measurements [seconds] - if your scanner
                                                        // is moving, this will be used in interpolating position
                                                        // of 3d points
                    float scan_time;                // time between scans [seconds]
                    float range_min;                // minimum range value [m]
                    float range_max;                // maximum range value [m]
                    sequence<float> ranges;         // range data [m] (Note: values < range_min or > range_max should be discarded)
                    sequence<float> intensities;    // intensity data [device-specific units].  If your device does not
                                                        // provide intensities, please leave the array empty.
                    };


    // IN ROS non sono presenti i messaggi SonarInfo, SonarScan

                // Non presente in STRESA 
                // const octet Range__ULTRASOUND = 0; 
                // const octet Range__INFRARED = 1; 
                // struct Range_{
                //     ros::std_msgs::msg::HeaderStandard header; 
                //     octet radiation_type; 
                //     float field_of_view; 
                //     float min_range; 
                //     float max_range; 
                //     float range; 
                // };


                /*
                    Funzionante
                */
                struct Image_{ 
                    std_msgs::msg::HeaderStandard header; 
                    unsigned long height;   // image height, that is, number of rows
                    unsigned long width;    // image width, that is, number of columns
                    string encoding;        // Encoding of pixels -- channel meaning, ordering, size
                                                // taken from the list of strings in include/sensor_msgs/image_encodings.h

                    octet is_bigendian;         //is this data bigendian?
                    unsigned long step;         //Full row length in bytes
                    sequence<octet> data;       //actual matrix data, size is (step * rows)
                }; 


                struct RegionOfInterest_{ 
                    unsigned long x_offset;     // Leftmost pixel of the ROI
                                                    //(0 if the ROI includes the left edge of the image)
                    unsigned long y_offset;     // Topmost pixel of the ROI
                                                    // (0 if the ROI includes the top edge of the image)
                    unsigned long height;       // Height of ROI
                    unsigned long width;        // Width of ROI
                    boolean do_rectify;         // True if a distinct rectified ROI should be calculated from the "raw"
                                                    // ROI in this message. Typically this should be False if the full image
                                                    // is captured (ROI not used), and True if a subwindow is captured (ROI
                                                    // used).
                }; 



                /*
                std_msgs/Header header
                uint32 height
                uint32 width
                string distortion_model
                float64[] D
                float64[9] K
                float64[9] R
                float64[12] P
                uint32 binning_x
                uint32 binning_y
                sensor_msgs/RegionOfInterest roi

                */

                struct CameraInfo_{ 
                    std_msgs::msg::HeaderStandard header; 
                    // The image dimensions with which the camera was calibrated. Normally
                    // this will be the full camera resolution in pixels.
                    unsigned long height; 
                    unsigned long width; 
                    string distortion_model;                        // The distortion model used. Supported models are listed in
                                                                        // sensor_msgs/distortion_models.h. For most cameras, "plumb_bob" - a
                                                                        // simple model of radial and tangential distortion - is sufficient.
                    sequence<double> D;                             // The distortion parameters, size depending on the distortion model.
                    double K[9];
                    double R[9];
                    double P[12];
                    unsigned long binning_x; 
                    unsigned long binning_y; 
                    sensor_msgs::msg::dds_::RegionOfInterest_ roi;                          // Region of interest (subwindow of full camera resolution), given in
                                                                        //  full resolution (unbinned) image coordinates. A particular ROI
                                                                        // always denotes the same window of pixels on the camera sensor,
                                                                        //  regardless of binning settings.
                                                                        // The default setting of roi (all values 0) is considered the same as
                                                                        //  full resolution (roi.width = width, roi.height = height).
                };

    // IN ROS non sono presenti i messaggi VisualObject e VisualSet

                struct JointState_{ 
                    std_msgs::msg::HeaderStandard header; 
                    sequence<string> name; 
                    sequence<double> position; 
                    sequence<double> velocity; 
                    sequence<double> effort; 
                };  

            };

        };

    };
#endif //__sensor_msgs__msg__idl  