// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TelemetryTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "TelemetryTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "Telemetry.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_SystemStats_type_identifier(
        TypeIdentifierPair& type_ids_SystemStats)
{

    ReturnCode_t return_code_SystemStats {eprosima::fastdds::dds::RETCODE_OK};
    return_code_SystemStats =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "SystemStats", type_ids_SystemStats);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_SystemStats)
    {
        StructTypeFlag struct_flags_SystemStats = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_SystemStats = "SystemStats";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_SystemStats;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_SystemStats;
        CompleteTypeDetail detail_SystemStats = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_SystemStats, ann_custom_SystemStats, type_name_SystemStats.to_string());
        CompleteStructHeader header_SystemStats;
        header_SystemStats = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_SystemStats);
        CompleteStructMemberSeq member_seq_SystemStats;
        {
            TypeIdentifierPair type_ids_packet_id;
            ReturnCode_t return_code_packet_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_packet_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_packet_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_packet_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "packet_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_packet_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_packet_id = 0x00000000;
            bool common_packet_id_ec {false};
            CommonStructMember common_packet_id {TypeObjectUtils::build_common_struct_member(member_id_packet_id, member_flags_packet_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_packet_id, common_packet_id_ec))};
            if (!common_packet_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure packet_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_packet_id = "packet_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_packet_id;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_packet_id = TypeObjectUtils::build_complete_member_detail(name_packet_id, member_ann_builtin_packet_id, ann_custom_SystemStats);
            CompleteStructMember member_packet_id = TypeObjectUtils::build_complete_struct_member(common_packet_id, detail_packet_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_packet_id);
        }
        {
            TypeIdentifierPair type_ids_roll;
            ReturnCode_t return_code_roll {eprosima::fastdds::dds::RETCODE_OK};
            return_code_roll =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_roll);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_roll)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "roll Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_roll = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_roll = 0x00000001;
            bool common_roll_ec {false};
            CommonStructMember common_roll {TypeObjectUtils::build_common_struct_member(member_id_roll, member_flags_roll, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_roll, common_roll_ec))};
            if (!common_roll_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure roll member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_roll = "roll";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_roll;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_roll = TypeObjectUtils::build_complete_member_detail(name_roll, member_ann_builtin_roll, ann_custom_SystemStats);
            CompleteStructMember member_roll = TypeObjectUtils::build_complete_struct_member(common_roll, detail_roll);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_roll);
        }
        {
            TypeIdentifierPair type_ids_pitch;
            ReturnCode_t return_code_pitch {eprosima::fastdds::dds::RETCODE_OK};
            return_code_pitch =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_pitch);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_pitch)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "pitch Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_pitch = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_pitch = 0x00000002;
            bool common_pitch_ec {false};
            CommonStructMember common_pitch {TypeObjectUtils::build_common_struct_member(member_id_pitch, member_flags_pitch, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_pitch, common_pitch_ec))};
            if (!common_pitch_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure pitch member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_pitch = "pitch";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_pitch;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_pitch = TypeObjectUtils::build_complete_member_detail(name_pitch, member_ann_builtin_pitch, ann_custom_SystemStats);
            CompleteStructMember member_pitch = TypeObjectUtils::build_complete_struct_member(common_pitch, detail_pitch);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_pitch);
        }
        {
            TypeIdentifierPair type_ids_yaw;
            ReturnCode_t return_code_yaw {eprosima::fastdds::dds::RETCODE_OK};
            return_code_yaw =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_yaw);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_yaw)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "yaw Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_yaw = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_yaw = 0x00000003;
            bool common_yaw_ec {false};
            CommonStructMember common_yaw {TypeObjectUtils::build_common_struct_member(member_id_yaw, member_flags_yaw, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_yaw, common_yaw_ec))};
            if (!common_yaw_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure yaw member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_yaw = "yaw";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_yaw;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_yaw = TypeObjectUtils::build_complete_member_detail(name_yaw, member_ann_builtin_yaw, ann_custom_SystemStats);
            CompleteStructMember member_yaw = TypeObjectUtils::build_complete_struct_member(common_yaw, detail_yaw);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_yaw);
        }
        {
            TypeIdentifierPair type_ids_altitude;
            ReturnCode_t return_code_altitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_altitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_altitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_altitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "altitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_altitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_altitude = 0x00000004;
            bool common_altitude_ec {false};
            CommonStructMember common_altitude {TypeObjectUtils::build_common_struct_member(member_id_altitude, member_flags_altitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_altitude, common_altitude_ec))};
            if (!common_altitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure altitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_altitude = "altitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_altitude;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_altitude = TypeObjectUtils::build_complete_member_detail(name_altitude, member_ann_builtin_altitude, ann_custom_SystemStats);
            CompleteStructMember member_altitude = TypeObjectUtils::build_complete_struct_member(common_altitude, detail_altitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_altitude);
        }
        {
            TypeIdentifierPair type_ids_latency_us;
            ReturnCode_t return_code_latency_us {eprosima::fastdds::dds::RETCODE_OK};
            return_code_latency_us =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_latency_us);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_latency_us)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "latency_us Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_latency_us = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_latency_us = 0x00000005;
            bool common_latency_us_ec {false};
            CommonStructMember common_latency_us {TypeObjectUtils::build_common_struct_member(member_id_latency_us, member_flags_latency_us, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_latency_us, common_latency_us_ec))};
            if (!common_latency_us_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure latency_us member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_latency_us = "latency_us";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_latency_us;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_latency_us = TypeObjectUtils::build_complete_member_detail(name_latency_us, member_ann_builtin_latency_us, ann_custom_SystemStats);
            CompleteStructMember member_latency_us = TypeObjectUtils::build_complete_struct_member(common_latency_us, detail_latency_us);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_latency_us);
        }
        {
            TypeIdentifierPair type_ids_speed;
            ReturnCode_t return_code_speed {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_speed);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed = 0x00000006;
            bool common_speed_ec {false};
            CommonStructMember common_speed {TypeObjectUtils::build_common_struct_member(member_id_speed, member_flags_speed, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed, common_speed_ec))};
            if (!common_speed_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed = "speed";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_speed = TypeObjectUtils::build_complete_member_detail(name_speed, member_ann_builtin_speed, ann_custom_SystemStats);
            CompleteStructMember member_speed = TypeObjectUtils::build_complete_struct_member(common_speed, detail_speed);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_speed);
        }
        {
            TypeIdentifierPair type_ids_deadline_missed;
            ReturnCode_t return_code_deadline_missed {eprosima::fastdds::dds::RETCODE_OK};
            return_code_deadline_missed =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_deadline_missed);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_deadline_missed)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "deadline_missed Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_deadline_missed = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_deadline_missed = 0x00000007;
            bool common_deadline_missed_ec {false};
            CommonStructMember common_deadline_missed {TypeObjectUtils::build_common_struct_member(member_id_deadline_missed, member_flags_deadline_missed, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_deadline_missed, common_deadline_missed_ec))};
            if (!common_deadline_missed_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure deadline_missed member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_deadline_missed = "deadline_missed";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_deadline_missed;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_deadline_missed = TypeObjectUtils::build_complete_member_detail(name_deadline_missed, member_ann_builtin_deadline_missed, ann_custom_SystemStats);
            CompleteStructMember member_deadline_missed = TypeObjectUtils::build_complete_struct_member(common_deadline_missed, detail_deadline_missed);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_deadline_missed);
        }
        {
            TypeIdentifierPair type_ids_status_msg;
            ReturnCode_t return_code_status_msg {eprosima::fastdds::dds::RETCODE_OK};
            return_code_status_msg =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_32", type_ids_status_msg);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_status_msg)
            {
                {
                    SBound bound = static_cast<SBound>(32);
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_32", type_ids_status_msg))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_32 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_status_msg = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_status_msg = 0x00000008;
            bool common_status_msg_ec {false};
            CommonStructMember common_status_msg {TypeObjectUtils::build_common_struct_member(member_id_status_msg, member_flags_status_msg, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status_msg, common_status_msg_ec))};
            if (!common_status_msg_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure status_msg member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_status_msg = "status_msg";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_status_msg;
            ann_custom_SystemStats.reset();
            CompleteMemberDetail detail_status_msg = TypeObjectUtils::build_complete_member_detail(name_status_msg, member_ann_builtin_status_msg, ann_custom_SystemStats);
            CompleteStructMember member_status_msg = TypeObjectUtils::build_complete_struct_member(common_status_msg, detail_status_msg);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemStats, member_status_msg);
        }
        CompleteStructType struct_type_SystemStats = TypeObjectUtils::build_complete_struct_type(struct_flags_SystemStats, header_SystemStats, member_seq_SystemStats);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_SystemStats, type_name_SystemStats.to_string(), type_ids_SystemStats))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "SystemStats already registered in TypeObjectRegistry for a different type.");
        }
    }
}
