#ifndef __std_msgs__msg__idl 
#define __std_msgs__msg__idl 

    module std_msgs{
        module msg{
            struct TimeStandard{ 
                long sec; 				// seconds since epoch
                unsigned long nanosec; 	// nanoseconds since sec
            }; 

            struct HeaderStandard{
                std_msgs::msg::TimeStandard stamp;        
                string frame_id;        // Frame this data is associated with
            };

        };
    };

#endif