// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Telemetry.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Telemetry.hpp"

#include "TelemetryTypeObject.hpp"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>




SystemStats::SystemStats()
{
    // Just to register all known types
    registerTelemetryTypes();
}

SystemStats::~SystemStats()
{
}

SystemStats::SystemStats(
        const SystemStats& x)
{
    m_packet_id = x.m_packet_id;
    m_roll = x.m_roll;
    m_pitch = x.m_pitch;
    m_yaw = x.m_yaw;
    m_altitude = x.m_altitude;
    m_speed = x.m_speed;
    m_landing_mode = x.m_landing_mode;
    m_status_msg = x.m_status_msg;
}

SystemStats::SystemStats(
        SystemStats&& x) noexcept
{
    m_packet_id = x.m_packet_id;
    m_roll = x.m_roll;
    m_pitch = x.m_pitch;
    m_yaw = x.m_yaw;
    m_altitude = x.m_altitude;
    m_speed = x.m_speed;
    m_landing_mode = x.m_landing_mode;
    m_status_msg = std::move(x.m_status_msg);
}

SystemStats& SystemStats::operator =(
        const SystemStats& x)
{

    m_packet_id = x.m_packet_id;
    m_roll = x.m_roll;
    m_pitch = x.m_pitch;
    m_yaw = x.m_yaw;
    m_altitude = x.m_altitude;
    m_speed = x.m_speed;
    m_landing_mode = x.m_landing_mode;
    m_status_msg = x.m_status_msg;
    return *this;
}

SystemStats& SystemStats::operator =(
        SystemStats&& x) noexcept
{

    m_packet_id = x.m_packet_id;
    m_roll = x.m_roll;
    m_pitch = x.m_pitch;
    m_yaw = x.m_yaw;
    m_altitude = x.m_altitude;
    m_speed = x.m_speed;
    m_landing_mode = x.m_landing_mode;
    m_status_msg = std::move(x.m_status_msg);
    return *this;
}

bool SystemStats::operator ==(
        const SystemStats& x) const
{
    return (m_packet_id == x.m_packet_id &&
           m_roll == x.m_roll &&
           m_pitch == x.m_pitch &&
           m_yaw == x.m_yaw &&
           m_altitude == x.m_altitude &&
           m_speed == x.m_speed &&
           m_landing_mode == x.m_landing_mode &&
           m_status_msg == x.m_status_msg);
}

bool SystemStats::operator !=(
        const SystemStats& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member packet_id
 * @param _packet_id New value for member packet_id
 */
void SystemStats::packet_id(
        uint32_t _packet_id)
{
    m_packet_id = _packet_id;
}

/*!
 * @brief This function returns the value of member packet_id
 * @return Value of member packet_id
 */
uint32_t SystemStats::packet_id() const
{
    return m_packet_id;
}

/*!
 * @brief This function returns a reference to member packet_id
 * @return Reference to member packet_id
 */
uint32_t& SystemStats::packet_id()
{
    return m_packet_id;
}


/*!
 * @brief This function sets a value in member roll
 * @param _roll New value for member roll
 */
void SystemStats::roll(
        float _roll)
{
    m_roll = _roll;
}

/*!
 * @brief This function returns the value of member roll
 * @return Value of member roll
 */
float SystemStats::roll() const
{
    return m_roll;
}

/*!
 * @brief This function returns a reference to member roll
 * @return Reference to member roll
 */
float& SystemStats::roll()
{
    return m_roll;
}


/*!
 * @brief This function sets a value in member pitch
 * @param _pitch New value for member pitch
 */
void SystemStats::pitch(
        float _pitch)
{
    m_pitch = _pitch;
}

/*!
 * @brief This function returns the value of member pitch
 * @return Value of member pitch
 */
float SystemStats::pitch() const
{
    return m_pitch;
}

/*!
 * @brief This function returns a reference to member pitch
 * @return Reference to member pitch
 */
float& SystemStats::pitch()
{
    return m_pitch;
}


/*!
 * @brief This function sets a value in member yaw
 * @param _yaw New value for member yaw
 */
void SystemStats::yaw(
        float _yaw)
{
    m_yaw = _yaw;
}

/*!
 * @brief This function returns the value of member yaw
 * @return Value of member yaw
 */
float SystemStats::yaw() const
{
    return m_yaw;
}

/*!
 * @brief This function returns a reference to member yaw
 * @return Reference to member yaw
 */
float& SystemStats::yaw()
{
    return m_yaw;
}


/*!
 * @brief This function sets a value in member altitude
 * @param _altitude New value for member altitude
 */
void SystemStats::altitude(
        float _altitude)
{
    m_altitude = _altitude;
}

/*!
 * @brief This function returns the value of member altitude
 * @return Value of member altitude
 */
float SystemStats::altitude() const
{
    return m_altitude;
}

/*!
 * @brief This function returns a reference to member altitude
 * @return Reference to member altitude
 */
float& SystemStats::altitude()
{
    return m_altitude;
}


/*!
 * @brief This function sets a value in member speed
 * @param _speed New value for member speed
 */
void SystemStats::speed(
        float _speed)
{
    m_speed = _speed;
}

/*!
 * @brief This function returns the value of member speed
 * @return Value of member speed
 */
float SystemStats::speed() const
{
    return m_speed;
}

/*!
 * @brief This function returns a reference to member speed
 * @return Reference to member speed
 */
float& SystemStats::speed()
{
    return m_speed;
}


/*!
 * @brief This function sets a value in member landing_mode
 * @param _landing_mode New value for member landing_mode
 */
void SystemStats::landing_mode(
        bool _landing_mode)
{
    m_landing_mode = _landing_mode;
}

/*!
 * @brief This function returns the value of member landing_mode
 * @return Value of member landing_mode
 */
bool SystemStats::landing_mode() const
{
    return m_landing_mode;
}

/*!
 * @brief This function returns a reference to member landing_mode
 * @return Reference to member landing_mode
 */
bool& SystemStats::landing_mode()
{
    return m_landing_mode;
}


/*!
 * @brief This function copies the value in member status_msg
 * @param _status_msg New value to be copied in member status_msg
 */
void SystemStats::status_msg(
        const eprosima::fastcdr::fixed_string<32>& _status_msg)
{
    m_status_msg = _status_msg;
}

/*!
 * @brief This function moves the value in member status_msg
 * @param _status_msg New value to be moved in member status_msg
 */
void SystemStats::status_msg(
        eprosima::fastcdr::fixed_string<32>&& _status_msg)
{
    m_status_msg = std::move(_status_msg);
}

/*!
 * @brief This function returns a constant reference to member status_msg
 * @return Constant reference to member status_msg
 */
const eprosima::fastcdr::fixed_string<32>& SystemStats::status_msg() const
{
    return m_status_msg;
}

/*!
 * @brief This function returns a reference to member status_msg
 * @return Reference to member status_msg
 */
eprosima::fastcdr::fixed_string<32>& SystemStats::status_msg()
{
    return m_status_msg;
}


// Include auxiliary functions like for serializing/deserializing.
#include "TelemetryCdrAux.ipp"

