// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TelemetryPubSubTypes.h
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_TELEMETRY_PUBSUBTYPES_H_
#define _FAST_DDS_GENERATED_TELEMETRY_PUBSUBTYPES_H_

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>
#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>

#include "Telemetry.hpp"






/*!
 * @brief This class represents the TopicDataType of the type SystemStats defined by the user in the IDL file.
 * @ingroup Telemetry
 */
class SystemStatsPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef SystemStats type;

    eProsima_user_DllExport SystemStatsPubSubType();

    eProsima_user_DllExport ~SystemStatsPubSubType();

    eProsima_user_DllExport bool serialize(
            void* data,
            eprosima::fastdds::rtps::SerializedPayload_t* payload)
    {
        return serialize(data, payload, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
    }

    eProsima_user_DllExport bool serialize(
            void* data,
            eprosima::fastdds::rtps::SerializedPayload_t* payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation);

    eProsima_user_DllExport bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t* payload,
            void* data);

    eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
            void* data)
    {
        return getSerializedSizeProvider(data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
    }

    eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
            void* data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation);

    eProsima_user_DllExport bool getKey(
            void* data,
            eprosima::fastdds::rtps::InstanceHandle_t* ihandle,
            bool force_md5 = false);

    eProsima_user_DllExport void* createData();

    eProsima_user_DllExport void deleteData(
            void* data);

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const
    {
        return false;
    }

    eProsima_user_DllExport inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
            void* memory) const
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    unsigned char* m_keyBuffer;

    bool serialize(const void* data, eprosima::fastdds::rtps::SerializedPayload_t& payload, eprosima::fastdds::dds::DataRepresentationId_t data_rep) override { return serialize(const_cast<void*>(data), &payload); }
    bool deserialize(eprosima::fastdds::rtps::SerializedPayload_t& payload, void* data) override { return deserialize(&payload, data); }
    uint32_t calculate_serialized_size(const void* data, eprosima::fastdds::dds::DataRepresentationId_t data_rep) override { return getSerializedSizeProvider(const_cast<void*>(data))(); }
    bool compute_key(const void* data, eprosima::fastdds::rtps::InstanceHandle_t& ihandle, bool force_md5) override { return getKey(const_cast<void*>(data), &ihandle, force_md5); }
    bool compute_key(eprosima::fastdds::rtps::SerializedPayload_t& payload, eprosima::fastdds::rtps::InstanceHandle_t& ihandle, bool force_md5) override { return false; }
    void* create_data() override { return createData(); }
    void delete_data(void* data) override { deleteData(data); }
};

#endif // _FAST_DDS_GENERATED_TELEMETRY_PUBSUBTYPES_H_

