struct SystemStats
{
    unsigned long packet_id;
    float roll;
    float pitch;
    float yaw;
    float altitude;     // NUOVO: Altitudine in metri
    float latency_us;
    boolean deadline_missed;
    string<32> status_msg;
};
