// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file service_msgs.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SERVICE_MSGS_H_
#define _FAST_DDS_GENERATED_SERVICE_MSGS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SERVICE_MSGS_SOURCE)
#define SERVICE_MSGS_DllAPI __declspec( dllexport )
#else
#define SERVICE_MSGS_DllAPI __declspec( dllimport )
#endif // SERVICE_MSGS_SOURCE
#else
#define SERVICE_MSGS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SERVICE_MSGS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure Request defined by the user in the IDL file.
 * @ingroup service_msgs
 */
class Request
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Request();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Request();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request(
            const Request& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request(
            Request&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request& operator =(
            const Request& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request& operator =(
            Request&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Request object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Request& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Request object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Request& x) const;

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            int32_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport int32_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport int32_t& id();


    /*!
     * @brief This function copies the value in member operation
     * @param _operation New value to be copied in member operation
     */
    eProsima_user_DllExport void operation(
            const std::string& _operation);

    /*!
     * @brief This function moves the value in member operation
     * @param _operation New value to be moved in member operation
     */
    eProsima_user_DllExport void operation(
            std::string&& _operation);

    /*!
     * @brief This function returns a constant reference to member operation
     * @return Constant reference to member operation
     */
    eProsima_user_DllExport const std::string& operation() const;

    /*!
     * @brief This function returns a reference to member operation
     * @return Reference to member operation
     */
    eProsima_user_DllExport std::string& operation();


    /*!
     * @brief This function sets a value in member data_a
     * @param _data_a New value for member data_a
     */
    eProsima_user_DllExport void data_a(
            double _data_a);

    /*!
     * @brief This function returns the value of member data_a
     * @return Value of member data_a
     */
    eProsima_user_DllExport double data_a() const;

    /*!
     * @brief This function returns a reference to member data_a
     * @return Reference to member data_a
     */
    eProsima_user_DllExport double& data_a();


    /*!
     * @brief This function sets a value in member data_b
     * @param _data_b New value for member data_b
     */
    eProsima_user_DllExport void data_b(
            double _data_b);

    /*!
     * @brief This function returns the value of member data_b
     * @return Value of member data_b
     */
    eProsima_user_DllExport double data_b() const;

    /*!
     * @brief This function returns a reference to member data_b
     * @return Reference to member data_b
     */
    eProsima_user_DllExport double& data_b();

private:

    int32_t m_id{0};
    std::string m_operation;
    double m_data_a{0.0};
    double m_data_b{0.0};

};


/*!
 * @brief This class represents the structure Reply defined by the user in the IDL file.
 * @ingroup service_msgs
 */
class Reply
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Reply();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Reply();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Reply that will be copied.
     */
    eProsima_user_DllExport Reply(
            const Reply& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Reply that will be copied.
     */
    eProsima_user_DllExport Reply(
            Reply&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Reply that will be copied.
     */
    eProsima_user_DllExport Reply& operator =(
            const Reply& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Reply that will be copied.
     */
    eProsima_user_DllExport Reply& operator =(
            Reply&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Reply object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Reply& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Reply object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Reply& x) const;

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            int32_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport int32_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport int32_t& id();


    /*!
     * @brief This function sets a value in member correct
     * @param _correct New value for member correct
     */
    eProsima_user_DllExport void correct(
            bool _correct);

    /*!
     * @brief This function returns the value of member correct
     * @return Value of member correct
     */
    eProsima_user_DllExport bool correct() const;

    /*!
     * @brief This function returns a reference to member correct
     * @return Reference to member correct
     */
    eProsima_user_DllExport bool& correct();


    /*!
     * @brief This function sets a value in member result
     * @param _result New value for member result
     */
    eProsima_user_DllExport void result(
            double _result);

    /*!
     * @brief This function returns the value of member result
     * @return Value of member result
     */
    eProsima_user_DllExport double result() const;

    /*!
     * @brief This function returns a reference to member result
     * @return Reference to member result
     */
    eProsima_user_DllExport double& result();

private:

    int32_t m_id{0};
    bool m_correct{false};
    double m_result{0.0};

};

#endif // _FAST_DDS_GENERATED_SERVICE_MSGS_H_



