#ifndef __geometry_msgs__msg__idl 
#define __geometry_msgs__msg__idl 

#include "std_msgs.idl"

module geometry_msgs {
    module msg {
        module dds_ {

            struct Point32_ {
                float x;
                float y;
                float z;
            };
            
            struct Polygon_ {
                sequence<geometry_msgs::msg::dds_::Point32_> points;
            };
            
            struct PolygonStamped_ {
                std_msgs::msg::HeaderStandard header;
                geometry_msgs::msg::dds_::Polygon_ polygon;
            };


            struct Point_ {
                double x;
                double y;
                double z;
            };

            struct Quaternion_ {
                double x;
                double y;
                double z;
                double w;
            };

            struct Transform_ {
                geometry_msgs::msg::dds_::Point_ translation;
                geometry_msgs::msg::dds_::Quaternion_ rotation;
            };

            struct TransformStamped_ {
                std_msgs::msg::HeaderStandard header;
                string child_frame_id;
                geometry_msgs::msg::dds_::Transform_ transform;
            };
            
            struct Pose_{
                geometry_msgs::msg::dds_::Point_ position;
                geometry_msgs::msg::dds_::Quaternion_ orientation;
            };
            
	    struct PoseArray_{
                std_msgs::msg::HeaderStandard header;
                sequence<geometry_msgs::msg::dds_::Pose_> poses;
            };

            struct PoseWithCovariance_{
                geometry_msgs::msg::dds_::Pose_ pose;
                double covariance[36];
            };

            struct PoseStamped_{
                std_msgs::msg::HeaderStandard header;
                geometry_msgs::msg::dds_::Pose_ pose;
            };
            
            struct Vector3_{ 
                double x; 
                double y; 
                double z; 
            }; 

            struct Twist_{
                geometry_msgs::msg::dds_::Vector3_ linear;
                geometry_msgs::msg::dds_::Vector3_ angular;
            };

            struct TwistWithCovariance_ {
                geometry_msgs::msg::dds_::Twist_ twist;
                double covariance[36];
            };            
        };
    };
};

#endif
